Project DreamTeam: Core/Src/ATcommands.c File Reference
ATcommands.c File Reference
#include "ATcommands.h"
Functions
int at_test_command (char *buffer, transmit_t tx, char *cmd)
Write a given command to buffer with the '=?' suffix for testing.
int at_query_command (char *buffer, transmit_t tx, char *cmd)
Write a given command to buffer with the '?' suffix for querying.
int at_set_command (char *buffer, transmit_t tx, char *cmd, const char *param_format,...)
Write a given command to buffer with the provided parameters as suffix.
int at_setn_command (char *buffer, transmit_t tx, size_t limit, char *cmd, const char *param_format,...)
Write a given command to buffer, up to a given limit, with the provided parameters as suffix, limited by.
int at_execute_command (char *buffer, transmit_t tx, char *cmd)
Write a given command to buffer as provided.
bool at_handle_error (int ret_value)
handles errors from AT command functions. Serves as an error-handling wrapper for conditions
Function Documentation
at_execute_command()
int at_execute_command (char * buffer, transmit_t tx, char * cmd)
Write a given command to buffer as provided.
Note
Newline "\r\n" is always appended to the buffer
Parameters
buffer ... character buffer which will be written too. Should be big enough to hold AT_CMD_BUFFER_SIZE
tx ... a callback function, which sends the buffer upon successful buffer write
cmd ... an AT command template to use or a pre-made string
Returns
length of characters written on success, AT_CMD_ERROR on failure of the underlying printf-functions
Definition at line 85 of file ATcommands.c.
References AT_CMD_ERROR, and sprintf_().
at_handle_error()
bool at_handle_error (int ret_value)
handles errors from AT command functions. Serves as an error-handling wrapper for conditions
Note
It prints "AT Command error.\r\n" on any error
Parameters
ret_value ... return value of AT command functions
Returns
true if it matches AT_CMD_ERROR, false otherwise
Definition at line 96 of file ATcommands.c.
References AT_CMD_ERROR, and printf_().
at_query_command()
int at_query_command (char * buffer, transmit_t tx, char * cmd)
Write a given command to buffer with the '?' suffix for querying.
Note
Newline "\r\n" is always appended to the buffer
Parameters
buffer ... character buffer which will be written too. Should be big enough to hold AT_CMD_BUFFER_SIZE
tx ... a callback function, which sends the buffer upon successful buffer write
cmd ... an AT command template to use
Returns
length of characters written on success, AT_CMD_ERROR on failure of the underlying printf-functions
Definition at line 21 of file ATcommands.c.
References AT_CMD_ERROR, and sprintf_().
at_set_command()
int at_set_command (char * buffer, transmit_t tx, char * cmd, const char * param_format, ...)
Write a given command to buffer with the provided parameters as suffix.
Note
Newline "\r\n" is always appended to the buffer
Parameters
buffer ... character buffer which will be written too. Should be big enough to hold AT_CMD_BUFFER_SIZE
tx ... a callback function, which sends the buffer upon successful buffer write
cmd ... an AT command template to use
param_format ... a format string for the parameters provided
Returns
length of characters written on success, AT_CMD_ERROR on failure of the underlying printf-functions
Definition at line 32 of file ATcommands.c.
References AT_CMD_ERROR, sprintf_(), and vsprintf_().
at_setn_command()
int at_setn_command (char * buffer, transmit_t tx, size_t limit, char * cmd, const char * param_format, ...)
Write a given command to buffer, up to a given limit, with the provided parameters as suffix, limited by.
Note
Newline "\r\n" is always appended to the buffer
Parameters
buffer ... character buffer which will be written too. Should be big enough to hold AT_CMD_BUFFER_SIZE
tx ... a callback function, which sends the buffer upon successful buffer write
limit ... an upper limit of characters to write. Writing less is possible.
cmd ... an AT command template to use
param_format ... a format string for the parameters provided
Returns
length of characters written on success, AT_CMD_ERROR on failure of the underlying printf-functions
Definition at line 58 of file ATcommands.c.
References AT_CMD_ERROR, sprintf_(), and vsnprintf_().
at_test_command()
int at_test_command (char * buffer, transmit_t tx, char * cmd)
Write a given command to buffer with the '=?' suffix for testing.
Note
Newline "\r\n" is always appended to the buffer
Parameters
buffer ... character buffer which will be written too. Should be big enough to hold AT_CMD_BUFFER_SIZE
tx ... a callback function, which sends the buffer upon successful buffer write
cmd ... a command template to use
Returns
length of characters written on success, AT_CMD_ERROR on failure of the underlying printf-functions
Definition at line 10 of file ATcommands.c.
References AT_CMD_ERROR, and sprintf_().