Project DreamTeam: Core/Src/application.c File Reference
application.c File Reference
#include <application.h>
#include "parser.h"
#include "wifi-ble.h"
#include "console.h"
#include "webserver.h"
#include "heartrateReceiver.h"
Functions
void StartInitTask (void *argument)
Function implementing the initTask thread.
APPLICATION_RETVAL acquire_semaphore (osSemaphoreId_t semaphore, uint32_t timeout)
Attempts to acquire a semaphore with the given timeout.
APPLICATION_RETVAL release_semaphore (osSemaphoreId_t semaphore)
Attempts to release a semaphore.
Variables
const char * newLine = "\r\n"
parser_module_t parser_module
osThreadId_t parserInitThreadId = NULL
const osThreadAttr_t parserInit_attr
osThreadId_t parserThreadId = NULL
uint32_t parserThreadStack [PARSER_MODULE_STACK_SIZE]
StaticTask_t parserThreadTCB
const osThreadAttr_t parser_attr
char request_buffer [PARSER_REQUEST_BUFFER_SIZE] = {0}
char response_buffer [PARSER_RESPONSE_BUFFER_SIZE] = {0}
const char * HTTP_HEADER = "HTTP/1.1 200 OK\r\n"
const char * HTTP_CONTENT_TYPE_HTML = "Content-type: text/html\r\n"
const char * HTTP_CONTENT_TYPE_TEXT = "Content-type: text/plain\r\n"
const char * HTTP_CONTENT_TYPE_JSON = "Content-type: application/json\r\n"
const char * HTTP_CONTENT_LENGTH_TEMPLATE = "Content-Length: %hu\r\nCache-Control: no-cache, must-revalidate\r\n\r\n"
const char * HTML_TEMPLATE = "<!DOCTYPE html><html><head><title>HEARTMONITOR</title><link rel='icon' href='data:,'><style>.bar{min-width:20px;display:inline-block;margin:5px;background-color: #4CAF50}#c-hr,#c-hr-c{background-color:lightgreen;}</style></head><body><button id='b'>Start</button><h3 id='hr'>HR:</h3><div id='c-hr'></div><h3 id='hr-c'>HRCALC:</h3><div id='c-hr-c'></div><script>let h=[],hc=[],T=2000,max=window.innerWidth/5,cHR=document.getElementById('c-hr'),cHRC=document.getElementById('c-hr-c'),hr=document.getElementById('hr'),hrC=document.getElementById('hr-c'),createBar=(v,c)=>{let b=document.createElement('div');b.className='bar';b.style.height=v+'px';b.textContent=v;c.appendChild(b);},updatePage=async()=>{let C=new AbortController(),S=C.signal;setTimeout(()=>C.abort(),T);let R=await fetch('http://%s:%s',{method:'GET',headers:{'Accept':'application/json'},S});if(R.ok){let r=await R.json();h.push(r.HR);hc.push(r.HRCALC);while(h.length>max){h.shift();}while(hc.length>max){hc.shift();}cHR.innerHTML='';cHRC.innerHTML='';h.forEach((v,i)=>{createBar(v,cHR);});hc.forEach((v,i)=>{createBar(v,cHRC);});hr.innerHTML='HR: '+r.HR;hrC.innerHTML='HRCALC: '+r.HRCALC;}else{console.error('HTTP error: '+R.status);}};b.onclick=()=>{if(b.innerText=='Start'){pollingInterval=setInterval(updatePage,T);b.innerText='Stop';}else{clearInterval(pollingInterval);b.innerText='Start';}};</script></body></html>"
wifible_module_t wifible_module
osThreadId_t wifibleInitThreadId = NULL
const osThreadAttr_t wifibleInit_attr
osThreadId_t wifibleThreadId = NULL
uint32_t wifibleThreadStack [WIFIBLE_MODULE_STACK_SIZE]
StaticTask_t wifibleThreadTCB
const osThreadAttr_t wifible_attr
uint8_t uart1Buffer [WIFIBLE_UART_BUFFER_SIZE]
char * newMsg = NULL
uint8_t responseLink = 0
uint8_t requestType = 0
uint8_t clients [4] = {0}
char update [MAX_UPDATE_SIZE] = {0}
char update_response [MAX_UPDATE_SIZE] = {0}
char page [MAX_PAGE_SIZE] = {0}
char page_response [MAX_PAGE_SIZE] = {0}
uint16_t page_response_length = 0
console_module_t console_module
osThreadId_t consoleInitThreadId = NULL
const osThreadAttr_t consoleInit_attr
osThreadId_t consoleThreadId = NULL
uint32_t consoleThreadStack [CONSOLE_MODULE_STACK_SIZE]
StaticTask_t consoleThreadTCB
const osThreadAttr_t console_attr
uint8_t uart2Buffer [CONSOLE_UART_BUFFER_SIZE] = {0}
uint16_t uart2BufferIndex = 0
uint8_t rx_byte = 0
char * input = NULL
hrReceiver_module_t hrReceiver_module
osThreadId_t hrReceiverInitThreadId = NULL
const osThreadAttr_t hrReceiverInit_attr
osThreadId_t hrReceiverThreadId = NULL
uint32_t hrReceiverThreadStack [HRRECEIVER_MODULE_STACK_SIZE]
StaticTask_t hrReceiverThreadTCB
const osThreadAttr_t hrReceiver_attr
uint8_t heartrate_ram [HEARTRATE_RAM_SIZE] = {0}
uint8_t heartrate_rx_offset = 0
uint8_t heartrate_read_index = 0
osSemaphoreId_t inputSem = NULL
StaticSemaphore_t inputSem_cb
osSemaphoreAttr_t inputSem_attr
osSemaphoreId_t msgSem = NULL
StaticSemaphore_t msgSem_cb
osSemaphoreAttr_t msgSem_attr
osSemaphoreId_t httpSem = NULL
StaticSemaphore_t httpSem_cb
osSemaphoreAttr_t httpSem_attr
osSemaphoreId_t i2cSem = NULL
StaticSemaphore_t i2cSem_cb
osSemaphoreAttr_t i2cSem_attr
Function Documentation
acquire_semaphore()
APPLICATION_RETVAL acquire_semaphore (osSemaphoreId_t semaphore, uint32_t timeout)
Attempts to acquire a semaphore with the given timeout.
Parameters
semaphore ... id of semaphore to get
timeout ... will return after specified timeout
Returns
SEMAPHORE_FAILURE on any osFailure and APPLICATION_OK on success
Definition at line 231 of file application.c.
References APPLICATION_OK, osStatusHandler(), and SEMAPHORE_FAILURE.
release_semaphore()
APPLICATION_RETVAL release_semaphore (osSemaphoreId_t semaphore)
Attempts to release a semaphore.
Parameters
semaphore ... id of semaphore to release
Returns
SEMAPHORE_FAILURE on any osFailure and APPLICATION_OK on success
Definition at line 238 of file application.c.
References APPLICATION_OK, osStatusHandler(), and SEMAPHORE_FAILURE.
StartInitTask()
__weak void StartInitTask (void * argument)
Function implementing the initTask thread.
Parameters
argument Not used
Return values
None
Definition at line 208 of file application.c.
References CONSOLE_MODULE_INIT_NAME, consoleInit_attr, consoleInitThreadId, HEARTRATE_RAM_SIZE, HRRECEIVER_MODULE_INIT_NAME, hrReceiverInit_attr, hrReceiverInitThreadId, HTTP_INIT_COUNT, HTTP_MAX_COUNT, httpSem, httpSem_attr, i2cSem, i2cSem_attr, INPUT_INIT_COUNT, INPUT_MAX_COUNT, inputSem, inputSem_attr, MESSAGE_INIT_COUNT, MESSAGE_MAX_COUNT, msgSem, msgSem_attr, newLine, PARSER_MODULE_INIT_NAME, parserInit_attr, parserInitThreadId, printf_(), StartConsoleInterface(), StartHrReceiver(), StartParser(), StartWebserverModule(), StartWifiBleModule(), threadErrorHandler(), WEBSERVER_MODULE_INIT_NAME, WIFIBLE_MODULE_INIT_NAME, wifibleInit_attr, and wifibleInitThreadId.
Variable Documentation
clients
uint8_t clients[4] = {0}
Definition at line 90 of file application.c.
console_attr
const osThreadAttr_t console_attr
Initial value:
= {
    .name = CONSOLE_MODULE_NAME,
    .priority = (osPriority_t) osPriorityNormal,
    .stack_size = CONSOLE_MODULE_STACK_SIZE * 4,
    .stack_mem = consoleThreadStack,
    .cb_mem = &consoleThreadTCB,
    .cb_size = sizeof(StaticTask_t)
}
Definition at line 111 of file application.c.
console_module
console_module_t console_module
Initial value:
= {
    .module_flags = FEEDBACK_ON|INPUT_ON
}
Definition at line 99 of file application.c.
consoleInit_attr
const osThreadAttr_t consoleInit_attr
Initial value:
= {
    .name = CONSOLE_MODULE_INIT_NAME,
    .priority = (osPriority_t) osPriorityBelowNormal3,
    .stack_size = MODULE_INIT_SIZE * 4,
}
Definition at line 103 of file application.c.
consoleInitThreadId
osThreadId_t consoleInitThreadId = NULL
Definition at line 102 of file application.c.
consoleThreadId
osThreadId_t consoleThreadId = NULL
Definition at line 108 of file application.c.
consoleThreadStack
uint32_t consoleThreadStack[CONSOLE_MODULE_STACK_SIZE]
Definition at line 109 of file application.c.
consoleThreadTCB
StaticTask_t consoleThreadTCB
Definition at line 110 of file application.c.
heartrate_ram
uint8_t heartrate_ram[HEARTRATE_RAM_SIZE] = {0}
Definition at line 172 of file application.c.
heartrate_read_index
uint8_t heartrate_read_index = 0
Definition at line 174 of file application.c.
heartrate_rx_offset
uint8_t heartrate_rx_offset = 0
Definition at line 173 of file application.c.
hrReceiver_attr
const osThreadAttr_t hrReceiver_attr
Initial value:
= {
    .name = HRRECEIVER_MODULE_NAME,
    .priority = (osPriority_t) osPriorityNormal,
    .stack_size = HRRECEIVER_MODULE_STACK_SIZE * 4,
    .stack_mem = hrReceiverThreadStack,
    .cb_mem = &hrReceiverThreadTCB,
    .cb_size = sizeof(StaticTask_t)
}
Definition at line 164 of file application.c.
hrReceiver_module
hrReceiver_module_t hrReceiver_module
Initial value:
= {
        .module_flags = 0
}
Definition at line 152 of file application.c.
hrReceiverInit_attr
const osThreadAttr_t hrReceiverInit_attr
Initial value:
= {
    .name = HRRECEIVER_MODULE_INIT_NAME,
    .priority = (osPriority_t) osPriorityBelowNormal5,
    .stack_size = MODULE_INIT_SIZE * 4,
}
Definition at line 156 of file application.c.
hrReceiverInitThreadId
osThreadId_t hrReceiverInitThreadId = NULL
Definition at line 155 of file application.c.
hrReceiverThreadId
osThreadId_t hrReceiverThreadId = NULL
Definition at line 161 of file application.c.
hrReceiverThreadStack
uint32_t hrReceiverThreadStack[HRRECEIVER_MODULE_STACK_SIZE]
Definition at line 162 of file application.c.
hrReceiverThreadTCB
StaticTask_t hrReceiverThreadTCB
Definition at line 163 of file application.c.
HTML_TEMPLATE
const char* HTML_TEMPLATE = "<!DOCTYPE html><html><head><title>HEARTMONITOR</title><link rel='icon' href='data:,'><style>.bar{min-width:20px;display:inline-block;margin:5px;background-color: #4CAF50}#c-hr,#c-hr-c{background-color:lightgreen;}</style></head><body><button id='b'>Start</button><h3 id='hr'>HR:</h3><div id='c-hr'></div><h3 id='hr-c'>HRCALC:</h3><div id='c-hr-c'></div><script>let h=[],hc=[],T=2000,max=window.innerWidth/5,cHR=document.getElementById('c-hr'),cHRC=document.getElementById('c-hr-c'),hr=document.getElementById('hr'),hrC=document.getElementById('hr-c'),createBar=(v,c)=>{let b=document.createElement('div');b.className='bar';b.style.height=v+'px';b.textContent=v;c.appendChild(b);},updatePage=async()=>{let C=new AbortController(),S=C.signal;setTimeout(()=>C.abort(),T);let R=await fetch('http://%s:%s',{method:'GET',headers:{'Accept':'application/json'},S});if(R.ok){let r=await R.json();h.push(r.HR);hc.push(r.HRCALC);while(h.length>max){h.shift();}while(hc.length>max){hc.shift();}cHR.innerHTML='';cHRC.innerHTML='';h.forEach((v,i)=>{createBar(v,cHR);});hc.forEach((v,i)=>{createBar(v,cHRC);});hr.innerHTML='HR: '+r.HR;hrC.innerHTML='HRCALC: '+r.HRCALC;}else{console.error('HTTP error: '+R.status);}};b.onclick=()=>{if(b.innerText=='Start'){pollingInterval=setInterval(updatePage,T);b.innerText='Stop';}else{clearInterval(pollingInterval);b.innerText='Start';}};</script></body></html>"
Definition at line 61 of file application.c.
HTTP_CONTENT_LENGTH_TEMPLATE
const char* HTTP_CONTENT_LENGTH_TEMPLATE = "Content-Length: %hu\r\nCache-Control: no-cache, must-revalidate\r\n\r\n"
Definition at line 54 of file application.c.
HTTP_CONTENT_TYPE_HTML
const char* HTTP_CONTENT_TYPE_HTML = "Content-type: text/html\r\n"
Definition at line 50 of file application.c.
HTTP_CONTENT_TYPE_JSON
const char* HTTP_CONTENT_TYPE_JSON = "Content-type: application/json\r\n"
Definition at line 52 of file application.c.
HTTP_CONTENT_TYPE_TEXT
const char* HTTP_CONTENT_TYPE_TEXT = "Content-type: text/plain\r\n"
Definition at line 51 of file application.c.
HTTP_HEADER
const char* HTTP_HEADER = "HTTP/1.1 200 OK\r\n"
Definition at line 47 of file application.c.
httpSem
osSemaphoreId_t httpSem = NULL
Definition at line 191 of file application.c.
httpSem_attr
osSemaphoreAttr_t httpSem_attr
Initial value:
= {
    .name = HTTP_SEMAPHORE,
    .cb_mem = &httpSem_cb,
    .cb_size = sizeof(StaticSemaphore_t)
}
Definition at line 193 of file application.c.
httpSem_cb
StaticSemaphore_t httpSem_cb
Definition at line 192 of file application.c.
i2cSem
osSemaphoreId_t i2cSem = NULL
Definition at line 198 of file application.c.
i2cSem_attr
osSemaphoreAttr_t i2cSem_attr
Initial value:
= {
    .name = I2C_SEMAPHORE,
    .cb_mem = &i2cSem_cb,
    .cb_size = sizeof(StaticSemaphore_t)
}
Definition at line 200 of file application.c.
i2cSem_cb
StaticSemaphore_t i2cSem_cb
Definition at line 199 of file application.c.
input
char* input = NULL
Definition at line 122 of file application.c.
inputSem
osSemaphoreId_t inputSem = NULL
Definition at line 177 of file application.c.
inputSem_attr
osSemaphoreAttr_t inputSem_attr
Initial value:
= {
    .name = INPUT_SEMAPHORE,
    .cb_mem = &inputSem_cb,
    .cb_size = sizeof(StaticSemaphore_t)
}
Definition at line 179 of file application.c.
inputSem_cb
StaticSemaphore_t inputSem_cb
Definition at line 178 of file application.c.
msgSem
osSemaphoreId_t msgSem = NULL
Definition at line 184 of file application.c.
msgSem_attr
osSemaphoreAttr_t msgSem_attr
Initial value:
= {
    .name = MESSAGE_SEMAPHORE,
    .cb_mem = &msgSem_cb,
    .cb_size = sizeof(StaticSemaphore_t)
}
Definition at line 186 of file application.c.
msgSem_cb
StaticSemaphore_t msgSem_cb
Definition at line 185 of file application.c.
newLine
const char* newLine = "\r\n"
Definition at line 19 of file application.c.
newMsg
char* newMsg = NULL
Definition at line 86 of file application.c.
page
char page[MAX_PAGE_SIZE] = {0}
Definition at line 93 of file application.c.
page_response
char page_response[MAX_PAGE_SIZE] = {0}
Definition at line 94 of file application.c.
page_response_length
uint16_t page_response_length = 0
Definition at line 95 of file application.c.
parser_attr
const osThreadAttr_t parser_attr
Initial value:
= {
    .name = PARSER_MODULE_NAME,
    .priority = (osPriority_t) osPriorityAboveNormal,
    .stack_size = PARSER_MODULE_STACK_SIZE * 4,
    .stack_mem = parserThreadStack,
    .cb_mem = &parserThreadTCB,
    .cb_size = sizeof(StaticTask_t)
}
Definition at line 34 of file application.c.
parser_module
parser_module_t parser_module
Initial value:
= {
    .module_flags = 0
}
Definition at line 22 of file application.c.
parserInit_attr
const osThreadAttr_t parserInit_attr
Initial value:
= {
    .name = PARSER_MODULE_INIT_NAME,
    .priority = (osPriority_t) osPriorityBelowNormal1,
    .stack_size = MODULE_INIT_SIZE * 4,
}
Definition at line 26 of file application.c.
parserInitThreadId
osThreadId_t parserInitThreadId = NULL
Definition at line 25 of file application.c.
parserThreadId
osThreadId_t parserThreadId = NULL
Definition at line 31 of file application.c.
parserThreadStack
uint32_t parserThreadStack[PARSER_MODULE_STACK_SIZE]
Definition at line 32 of file application.c.
parserThreadTCB
StaticTask_t parserThreadTCB
Definition at line 33 of file application.c.
request_buffer
char request_buffer[PARSER_REQUEST_BUFFER_SIZE] = {0}
Definition at line 42 of file application.c.
requestType
uint8_t requestType = 0
Definition at line 88 of file application.c.
response_buffer
char response_buffer[PARSER_RESPONSE_BUFFER_SIZE] = {0}
Definition at line 43 of file application.c.
responseLink
uint8_t responseLink = 0
Definition at line 87 of file application.c.
rx_byte
uint8_t rx_byte = 0
Definition at line 121 of file application.c.
uart1Buffer
uint8_t uart1Buffer[WIFIBLE_UART_BUFFER_SIZE]
Definition at line 85 of file application.c.
uart2Buffer
uint8_t uart2Buffer[CONSOLE_UART_BUFFER_SIZE] = {0}
Definition at line 119 of file application.c.
uart2BufferIndex
uint16_t uart2BufferIndex = 0
Definition at line 120 of file application.c.
update
char update[MAX_UPDATE_SIZE] = {0}
Definition at line 91 of file application.c.
update_response
char update_response[MAX_UPDATE_SIZE] = {0}
Definition at line 92 of file application.c.
wifible_attr
const osThreadAttr_t wifible_attr
Initial value:
= {
    .name = WIFIBLE_MODULE_NAME,
    .priority = (osPriority_t) osPriorityNormal,
    .stack_size = WIFIBLE_MODULE_STACK_SIZE * 4,
    .stack_mem = wifibleThreadStack,
    .cb_mem = &wifibleThreadTCB,
    .cb_size = sizeof(StaticTask_t)
}
Definition at line 77 of file application.c.
wifible_module
wifible_module_t wifible_module
Initial value:
= {
    .mode = WIFIBLE_WIRELESS_MODE
}
Definition at line 65 of file application.c.
wifibleInit_attr
const osThreadAttr_t wifibleInit_attr
Initial value:
= {
    .name = WIFIBLE_MODULE_INIT_NAME,
    .priority = (osPriority_t) osPriorityBelowNormal2,
    .stack_size = MODULE_INIT_SIZE * 4,
}
Definition at line 69 of file application.c.
wifibleInitThreadId
osThreadId_t wifibleInitThreadId = NULL
Definition at line 68 of file application.c.
wifibleThreadId
osThreadId_t wifibleThreadId = NULL
Definition at line 74 of file application.c.
wifibleThreadStack
uint32_t wifibleThreadStack[WIFIBLE_MODULE_STACK_SIZE]
Definition at line 75 of file application.c.
wifibleThreadTCB
StaticTask_t wifibleThreadTCB
Definition at line 76 of file application.c.