Project DreamTeam: Core/Inc/console.h File Reference
console.h File Reference
#include <application.h>
#include "FreeRTOS.h"
#include "cmsis_os2.h"
#include "usart.h"
#include "printf.h"
#include "string.h"
#include "helper.h"
Data Structures
struct console_module
A structure to provide flags for behaviour change of the module.
Macros
#define CONSOLE_MODULE_STACK_SIZE 512
#define CONSOLE_MODULE_NAME "CONSOLE"
#define CONSOLE_MODULE_INIT_NAME "ConsoleInit"
#define CONSOLE_RETVAL uint8_t
#define CONSOLE_UART_BUFFER_SIZE 128
#define CONSOLE_OK 0x00
#define CONSOLE_FAILED_COPY 0x01
#define CONSOLE_FAILED_SEMAPHORE 0x02
#define CONSOLE_FAILED_FLAG 0x04
#define CONSOLE_NEW_DATA 0x08
#define CONSOLE_NEW_COMMAND 0xC0
#define FEEDBACK_ON 0xE1
#define PREFIX_ON 0xE2
#define TIMESTAMP_ON 0xE4
#define INPUT_ON 0xE8
#define CONSOLE_NOT_IMPLEMENTED 0xFA
#define CONSOLE_MEM_ERROR 0xFB
#define CONSOLE_RESOURCE_ERROR 0xFC
#define CONSOLE_RW_ERROR 0xFD
#define CONSOLE_ENABLE_ERROR 0xFE
#define CONSOLE_INIT_ERROR 0xFF
Typedefs
typedef struct console_module console_module_t
A structure to provide flags for behaviour change of the module.
Functions
void StartConsoleInterface (void *argument)
An initialization task for this module.
void ConsoleMonitor (void *argument)
Main task for this module.
CONSOLE_RETVAL console_handle_rxByte ()
On RX_BYTE signal, handles a received byte from the serial console (USART2)
CONSOLE_RETVAL console_enter_copy ()
enters the memory copy function and also clears previously allocated memory
CONSOLE_RETVAL console_handle_newInput ()
On NEW_INPUT signal, processes a given user input and forward a copy to WIFIBLE module.
CONSOLE_RETVAL console_handle_bufferOverrun ()
On BUFFER_OVERRUN signal, all entered characters are deleted and user is informed.
CONSOLE_RETVAL console_prep_peripherals ()
Prepares peripherals used in this module. Module fails to function without it.
CONSOLE_RETVAL console_clear_buffer ()
Clears the current buffer for USART2 and sets everything to NUL-terminating characters.
bool console_failureHandler (CONSOLE_RETVAL value)
handles errors from console module functions. Serves as an error-handling wrapper for conditions
Macro Definition Documentation
CONSOLE_ENABLE_ERROR
#define CONSOLE_ENABLE_ERROR 0xFE
Definition at line 48 of file console.h.
CONSOLE_FAILED_COPY
#define CONSOLE_FAILED_COPY 0x01
Definition at line 31 of file console.h.
CONSOLE_FAILED_FLAG
#define CONSOLE_FAILED_FLAG 0x04
Definition at line 33 of file console.h.
CONSOLE_FAILED_SEMAPHORE
#define CONSOLE_FAILED_SEMAPHORE 0x02
Definition at line 32 of file console.h.
CONSOLE_INIT_ERROR
#define CONSOLE_INIT_ERROR 0xFF
Definition at line 49 of file console.h.
CONSOLE_MEM_ERROR
#define CONSOLE_MEM_ERROR 0xFB
Definition at line 45 of file console.h.
CONSOLE_MODULE_INIT_NAME
#define CONSOLE_MODULE_INIT_NAME "ConsoleInit"
Definition at line 26 of file console.h.
CONSOLE_MODULE_NAME
#define CONSOLE_MODULE_NAME "CONSOLE"
Definition at line 25 of file console.h.
CONSOLE_MODULE_STACK_SIZE
#define CONSOLE_MODULE_STACK_SIZE 512
Definition at line 24 of file console.h.
CONSOLE_NEW_COMMAND
#define CONSOLE_NEW_COMMAND 0xC0
Definition at line 36 of file console.h.
CONSOLE_NEW_DATA
#define CONSOLE_NEW_DATA 0x08
Definition at line 34 of file console.h.
CONSOLE_NOT_IMPLEMENTED
#define CONSOLE_NOT_IMPLEMENTED 0xFA
Definition at line 44 of file console.h.
CONSOLE_OK
#define CONSOLE_OK 0x00
Definition at line 30 of file console.h.
CONSOLE_RESOURCE_ERROR
#define CONSOLE_RESOURCE_ERROR 0xFC
Definition at line 46 of file console.h.
CONSOLE_RETVAL
#define CONSOLE_RETVAL uint8_t
Definition at line 27 of file console.h.
CONSOLE_RW_ERROR
#define CONSOLE_RW_ERROR 0xFD
Definition at line 47 of file console.h.
CONSOLE_UART_BUFFER_SIZE
#define CONSOLE_UART_BUFFER_SIZE 128
Definition at line 28 of file console.h.
FEEDBACK_ON
#define FEEDBACK_ON 0xE1
Definition at line 39 of file console.h.
INPUT_ON
#define INPUT_ON 0xE8
Definition at line 42 of file console.h.
PREFIX_ON
#define PREFIX_ON 0xE2
Definition at line 40 of file console.h.
TIMESTAMP_ON
#define TIMESTAMP_ON 0xE4
Definition at line 41 of file console.h.
Typedef Documentation
console_module_t
typedef struct console_module console_module_t
A structure to provide flags for behaviour change of the module.
Note
Currently there are no behaviour changes implemented.
Function Documentation
console_clear_buffer()
CONSOLE_RETVAL console_clear_buffer ()
Clears the current buffer for USART2 and sets everything to NUL-terminating characters.
Returns
either error or status macros, CONSOLE_OK on success
Definition at line 180 of file console.c.
References CONSOLE_OK, CONSOLE_UART_BUFFER_SIZE, uart2Buffer, and uart2BufferIndex.
console_enter_copy()
CONSOLE_RETVAL console_enter_copy ()
enters the memory copy function and also clears previously allocated memory
Returns
either error or status macros, CONSOLE_OK on success
Definition at line 126 of file console.c.
References acquire_semaphore(), CONSOLE_FAILED_COPY, CONSOLE_OK, input, inputSem, and MODULE_SEM_TIMEOUT.
console_failureHandler()
bool console_failureHandler (CONSOLE_RETVAL value)
handles errors from console module functions. Serves as an error-handling wrapper for conditions
Parameters
value ... return value of any CONSOLE module function
Returns
true on failure values, false on successful values
Definition at line 186 of file console.c.
References CONSOLE_ENABLE_ERROR, CONSOLE_FAILED_COPY, CONSOLE_FAILED_FLAG, CONSOLE_FAILED_SEMAPHORE, CONSOLE_INIT_ERROR, CONSOLE_NEW_DATA, CONSOLE_OK, CONSOLE_RESOURCE_ERROR, CONSOLE_RW_ERROR, newLine, and printf_().
console_handle_bufferOverrun()
CONSOLE_RETVAL console_handle_bufferOverrun ()
On BUFFER_OVERRUN signal, all entered characters are deleted and user is informed.
Returns
either error or status macros, CONSOLE_OK on success
Definition at line 163 of file console.c.
References console_clear_buffer(), CONSOLE_OK, newLine, printf_(), and uart2Buffer.
console_handle_newInput()
CONSOLE_RETVAL console_handle_newInput ()
On NEW_INPUT signal, processes a given user input and forward a copy to WIFIBLE module.
Returns
either error or status macros, CONSOLE_OK on success
Definition at line 136 of file console.c.
References console_enter_copy(), CONSOLE_FAILED_FLAG, CONSOLE_MEM_ERROR, CONSOLE_OK, CONSOLE_RETVAL, flagErrorHandler(), input, inputSem, NEW_INPUT, parserThreadId, release_semaphore(), uart2Buffer, and uart2BufferIndex.
console_handle_rxByte()
CONSOLE_RETVAL console_handle_rxByte ()
On RX_BYTE signal, handles a received byte from the serial console (USART2)
Returns
either error or status macros, CONSOLE_OK on success
Definition at line 95 of file console.c.
References BUFFER_OVERRUN, CONSOLE_NEW_DATA, CONSOLE_OK, CONSOLE_UART_BUFFER_SIZE, consoleThreadId, flagErrorHandler(), halStatusHandler(), huart2, newLine, printf_(), rx_byte, translate_UART_Error(), uart2Buffer, and uart2BufferIndex.
console_prep_peripherals()
CONSOLE_RETVAL console_prep_peripherals ()
Prepares peripherals used in this module. Module fails to function without it.
Returns
either error or status macros, CONSOLE_OK on success
Definition at line 170 of file console.c.
References CONSOLE_OK, CONSOLE_RESOURCE_ERROR, halStatusHandler(), huart2, printf_(), rx_byte, and translate_UART_Error().
ConsoleMonitor()
void ConsoleMonitor (void * argument)
Main task for this module.
Parameters
argument ... provide console_module_t for module behaviour change
Definition at line 59 of file console.c.
References BUFFER_OVERRUN, console_failureHandler(), console_handle_bufferOverrun(), console_handle_newInput(), console_handle_rxByte(), CONSOLE_NEW_DATA, CONSOLE_RETVAL, flagErrorHandler(), newLine, printf_(), RX_BYTE, and uart2BufferIndex.
StartConsoleInterface()
void StartConsoleInterface (void * argument)
An initialization task for this module.
Parameters
argument ... provide console_module_t for module behaviour change
Definition at line 49 of file console.c.
References console_attr, console_failureHandler(), CONSOLE_INIT_ERROR, console_prep_peripherals(), CONSOLE_RETVAL, ConsoleMonitor(), and consoleThreadId.