Project DreamTeam: Core/Src/console.c File Reference
console.c File Reference
#include "console.h"
Functions
void HAL_UART_RxCpltCallback (UART_HandleTypeDef *huart)
void StartConsoleInterface (void *argument)
An initialization task for this module.
void ConsoleMonitor (void *argument)
Main task for this module.
CONSOLE_RETVAL console_handle_rxByte ()
On RX_BYTE signal, handles a received byte from the serial console (USART2)
CONSOLE_RETVAL console_enter_copy ()
enters the memory copy function and also clears previously allocated memory
CONSOLE_RETVAL console_handle_newInput ()
On NEW_INPUT signal, processes a given user input and forward a copy to WIFIBLE module.
CONSOLE_RETVAL console_handle_bufferOverrun ()
On BUFFER_OVERRUN signal, all entered characters are deleted and user is informed.
CONSOLE_RETVAL console_prep_peripherals ()
Prepares peripherals used in this module. Module fails to function without it.
CONSOLE_RETVAL console_clear_buffer ()
Clears the current buffer for USART2 and sets everything to NUL-terminating characters.
bool console_failureHandler (CONSOLE_RETVAL value)
handles errors from console module functions. Serves as an error-handling wrapper for conditions
Variables
osThreadId_t consoleThreadId
const osThreadAttr_t console_attr
const char * newLine
uint8_t uart2Buffer [CONSOLE_UART_BUFFER_SIZE]
uint16_t uart2BufferIndex
uint8_t rx_byte
osSemaphoreId_t inputSem
osThreadId_t parserThreadId
char * input
Function Documentation
console_clear_buffer()
CONSOLE_RETVAL console_clear_buffer ()
Clears the current buffer for USART2 and sets everything to NUL-terminating characters.
Returns
either error or status macros, CONSOLE_OK on success
Definition at line 180 of file console.c.
References CONSOLE_OK, CONSOLE_UART_BUFFER_SIZE, uart2Buffer, and uart2BufferIndex.
console_enter_copy()
CONSOLE_RETVAL console_enter_copy ()
enters the memory copy function and also clears previously allocated memory
Returns
either error or status macros, CONSOLE_OK on success
Definition at line 126 of file console.c.
References acquire_semaphore(), CONSOLE_FAILED_COPY, CONSOLE_OK, input, inputSem, and MODULE_SEM_TIMEOUT.
console_failureHandler()
bool console_failureHandler (CONSOLE_RETVAL value)
handles errors from console module functions. Serves as an error-handling wrapper for conditions
Parameters
value ... return value of any CONSOLE module function
Returns
true on failure values, false on successful values
Definition at line 186 of file console.c.
References CONSOLE_ENABLE_ERROR, CONSOLE_FAILED_COPY, CONSOLE_FAILED_FLAG, CONSOLE_FAILED_SEMAPHORE, CONSOLE_INIT_ERROR, CONSOLE_NEW_DATA, CONSOLE_OK, CONSOLE_RESOURCE_ERROR, CONSOLE_RW_ERROR, newLine, and printf_().
console_handle_bufferOverrun()
CONSOLE_RETVAL console_handle_bufferOverrun ()
On BUFFER_OVERRUN signal, all entered characters are deleted and user is informed.
Returns
either error or status macros, CONSOLE_OK on success
Definition at line 163 of file console.c.
References console_clear_buffer(), CONSOLE_OK, newLine, printf_(), and uart2Buffer.
console_handle_newInput()
CONSOLE_RETVAL console_handle_newInput ()
On NEW_INPUT signal, processes a given user input and forward a copy to WIFIBLE module.
Returns
either error or status macros, CONSOLE_OK on success
Definition at line 136 of file console.c.
References console_enter_copy(), CONSOLE_FAILED_FLAG, CONSOLE_MEM_ERROR, CONSOLE_OK, CONSOLE_RETVAL, flagErrorHandler(), input, inputSem, NEW_INPUT, parserThreadId, release_semaphore(), uart2Buffer, and uart2BufferIndex.
console_handle_rxByte()
CONSOLE_RETVAL console_handle_rxByte ()
On RX_BYTE signal, handles a received byte from the serial console (USART2)
Returns
either error or status macros, CONSOLE_OK on success
Definition at line 95 of file console.c.
References BUFFER_OVERRUN, CONSOLE_NEW_DATA, CONSOLE_OK, CONSOLE_UART_BUFFER_SIZE, consoleThreadId, flagErrorHandler(), halStatusHandler(), huart2, newLine, printf_(), rx_byte, translate_UART_Error(), uart2Buffer, and uart2BufferIndex.
console_prep_peripherals()
CONSOLE_RETVAL console_prep_peripherals ()
Prepares peripherals used in this module. Module fails to function without it.
Returns
either error or status macros, CONSOLE_OK on success
Definition at line 170 of file console.c.
References CONSOLE_OK, CONSOLE_RESOURCE_ERROR, halStatusHandler(), huart2, printf_(), rx_byte, and translate_UART_Error().
ConsoleMonitor()
void ConsoleMonitor (void * argument)
Main task for this module.
Parameters
argument ... provide console_module_t for module behaviour change
Definition at line 59 of file console.c.
References BUFFER_OVERRUN, console_failureHandler(), console_handle_bufferOverrun(), console_handle_newInput(), console_handle_rxByte(), CONSOLE_NEW_DATA, CONSOLE_RETVAL, flagErrorHandler(), newLine, printf_(), RX_BYTE, and uart2BufferIndex.
HAL_UART_RxCpltCallback()
void HAL_UART_RxCpltCallback (UART_HandleTypeDef * huart)
Definition at line 26 of file console.c.
References consoleThreadId, flagErrorHandler(), halStatusHandler(), huart2, newLine, printf_(), rx_byte, RX_BYTE, and translate_UART_Error().
StartConsoleInterface()
void StartConsoleInterface (void * argument)
An initialization task for this module.
Parameters
argument ... provide console_module_t for module behaviour change
Definition at line 49 of file console.c.
References console_attr, console_failureHandler(), CONSOLE_INIT_ERROR, console_prep_peripherals(), CONSOLE_RETVAL, ConsoleMonitor(), and consoleThreadId.
Variable Documentation
console_attr
const osThreadAttr_t console_attr
Definition at line 111 of file application.c.
consoleThreadId
osThreadId_t consoleThreadId
Definition at line 108 of file application.c.
input
char* input
Definition at line 122 of file application.c.
inputSem
osSemaphoreId_t inputSem
Definition at line 177 of file application.c.
newLine
const char* newLine
Definition at line 19 of file application.c.
parserThreadId
osThreadId_t parserThreadId
Definition at line 31 of file application.c.
rx_byte
uint8_t rx_byte
Definition at line 121 of file application.c.
uart2Buffer
uint8_t uart2Buffer[CONSOLE_UART_BUFFER_SIZE]
Definition at line 119 of file application.c.
uart2BufferIndex
uint16_t uart2BufferIndex
Definition at line 120 of file application.c.