Project DreamTeam: Core/Inc/heartrateReceiver.h File Reference
heartrateReceiver.h File Reference
#include "application.h"
#include "FreeRTOS.h"
#include "cmsis_os2.h"
#include "i2c.h"
#include "stm32l4xx_ll_i2c.h"
#include "stdbool.h"
#include "printf.h"
#include "string.h"
#include "helper.h"
#include "stdio.h"
Data Structures
struct hrReceiver_module
A structure to provide flags for behaviour change of the module.
Macros
#define HRRECEIVER_MODULE_STACK_SIZE 512
#define HRRECEIVER_MODULE_NAME "hrRECEIVER"
#define HRRECEIVER_MODULE_INIT_NAME "hrReceiverInit"
#define HRRECEIVER_RETVAL uint8_t
#define HRRECEIVER_OK APPLICATION_OK
#define HRRECEIVER_FAILED 0x01
#define HRRECEIVER_RESOURCE_ERROR 0xFE
#define HRRECEIVER_INIT_ERROR 0xFF
Typedefs
typedef struct hrReceiver_module hrReceiver_module_t
A structure to provide flags for behaviour change of the module.
Functions
void StartHrReceiver (void *argument)
An initialization task for this module.
void HrReceiver (void *argument)
Main task for this module.
HRRECEIVER_RETVAL hrReceiver_handle_heartrate ()
On I2C_EVENT signal, processes the heartrate values.
HRRECEIVER_RETVAL hrReceiver_prep_peripherals ()
Prepares peripherals used in this module. Module fails to function without it.
bool hrReceiver_failureHandler (HRRECEIVER_RETVAL value)
handles errors from console module functions. Serves as an error-handling wrapper for conditions
Macro Definition Documentation
HRRECEIVER_FAILED
#define HRRECEIVER_FAILED 0x01
Definition at line 31 of file heartrateReceiver.h.
HRRECEIVER_INIT_ERROR
#define HRRECEIVER_INIT_ERROR 0xFF
Definition at line 34 of file heartrateReceiver.h.
HRRECEIVER_MODULE_INIT_NAME
#define HRRECEIVER_MODULE_INIT_NAME "hrReceiverInit"
Definition at line 27 of file heartrateReceiver.h.
HRRECEIVER_MODULE_NAME
#define HRRECEIVER_MODULE_NAME "hrRECEIVER"
Definition at line 26 of file heartrateReceiver.h.
HRRECEIVER_MODULE_STACK_SIZE
#define HRRECEIVER_MODULE_STACK_SIZE 512
Definition at line 25 of file heartrateReceiver.h.
HRRECEIVER_OK
#define HRRECEIVER_OK APPLICATION_OK
Definition at line 30 of file heartrateReceiver.h.
HRRECEIVER_RESOURCE_ERROR
#define HRRECEIVER_RESOURCE_ERROR 0xFE
Definition at line 33 of file heartrateReceiver.h.
HRRECEIVER_RETVAL
#define HRRECEIVER_RETVAL uint8_t
Definition at line 28 of file heartrateReceiver.h.
Typedef Documentation
hrReceiver_module_t
typedef struct hrReceiver_module hrReceiver_module_t
A structure to provide flags for behaviour change of the module.
Note
Currently there are no behaviour changes implemented.
Function Documentation
HrReceiver()
void HrReceiver (void * argument)
Main task for this module.
Parameters
argument ... provide hrReceiver_module_t for module behaviour change
Definition at line 244 of file heartrateReceiver.c.
References flagErrorHandler(), hrReceiver_failureHandler(), hrReceiver_handle_heartrate(), HRRECEIVER_RETVAL, I2C_EVENT, newLine, and printf_().
hrReceiver_failureHandler()
bool hrReceiver_failureHandler (HRRECEIVER_RETVAL value)
handles errors from console module functions. Serves as an error-handling wrapper for conditions
Parameters
value ... return value of any HRRECEIVER module function
Returns
true on failure values, false on successful values
Definition at line 310 of file heartrateReceiver.c.
References HRRECEIVER_FAILED, HRRECEIVER_INIT_ERROR, HRRECEIVER_OK, HRRECEIVER_RESOURCE_ERROR, newLine, and printf_().
hrReceiver_handle_heartrate()
HRRECEIVER_RETVAL hrReceiver_handle_heartrate ()
On I2C_EVENT signal, processes the heartrate values.
Note
There currently isn't any processing necessary, but the function can output debug functionality
Returns
either error or status macros, HRRECEIVER_OK on success
Definition at line 264 of file heartrateReceiver.c.
References heartrate_ram, HEARTRATE_RAM_SIZE, HRRECEIVER_OK, newLine, and printf_().
hrReceiver_prep_peripherals()
HRRECEIVER_RETVAL hrReceiver_prep_peripherals ()
Prepares peripherals used in this module. Module fails to function without it.
Returns
either error or status macros, HRRECEIVER_OK on success
Definition at line 280 of file heartrateReceiver.c.
References halStatusHandler(), heartrate_ram, hi2c3, HRRECEIVER_OK, HRRECEIVER_RESOURCE_ERROR, printf_(), and translate_I2C_Error().
StartHrReceiver()
void StartHrReceiver (void * argument)
An initialization task for this module.
Parameters
argument ... provide hrReceiver_module_t for module behaviour change
Definition at line 228 of file heartrateReceiver.c.
References HrReceiver(), hrReceiver_attr, hrReceiver_failureHandler(), hrReceiver_prep_peripherals(), HRRECEIVER_RETVAL, hrReceiverThreadId, newLine, newValue, osStatusHandler(), printf_(), and selfSendTimer.