Project DreamTeam: Core/Src/heartrateReceiver.c File Reference
heartrateReceiver.c File Reference
#include "heartrateReceiver.h"
Macros
#define I2C_USING_INTERRUPTS
Functions
void HAL_I2C_AddrCallback (I2C_HandleTypeDef *hi2c, uint8_t TransferDirection, uint16_t AddrMatchCode)
void HAL_I2C_ListenCpltCallback (I2C_HandleTypeDef *hi2c)
void HAL_I2C_SlaveRxCpltCallback (I2C_HandleTypeDef *hi2c)
void HAL_I2C_SlaveTxCpltCallback (I2C_HandleTypeDef *hi2c)
void StartHrReceiver (void *argument)
An initialization task for this module.
void HrReceiver (void *argument)
Main task for this module.
HRRECEIVER_RETVAL hrReceiver_handle_heartrate ()
On I2C_EVENT signal, processes the heartrate values.
void hrReceiver_i2c_callback ()
HRRECEIVER_RETVAL hrReceiver_prep_peripherals ()
Prepares peripherals used in this module. Module fails to function without it.
bool hrReceiver_failureHandler (HRRECEIVER_RETVAL value)
handles errors from console module functions. Serves as an error-handling wrapper for conditions
Variables
const char * newLine
osThreadId_t hrReceiverThreadId
osThreadAttr_t hrReceiver_attr
osSemaphoreId_t i2cSem
uint8_t heartrate_ram [HEARTRATE_RAM_SIZE]
uint8_t heartrate_rx_offset
osTimerId_t selfSendTimer
bool first = true
uint8_t newValue = 0
uint8_t selfAddress_write = (0x69 << 1)
uint8_t selfAddress_read = (0x69 << 1) | 1
Macro Definition Documentation
I2C_USING_INTERRUPTS
#define I2C_USING_INTERRUPTS
Definition at line 16 of file heartrateReceiver.c.
Function Documentation
HAL_I2C_AddrCallback()
void HAL_I2C_AddrCallback (I2C_HandleTypeDef * hi2c, uint8_t TransferDirection, uint16_t AddrMatchCode)
Definition at line 56 of file heartrateReceiver.c.
References halStatusHandler(), heartrate_rx_offset, newLine, printf_(), and translate_I2C_Error().
HAL_I2C_ListenCpltCallback()
void HAL_I2C_ListenCpltCallback (I2C_HandleTypeDef * hi2c)
Definition at line 92 of file heartrateReceiver.c.
References halStatusHandler(), newLine, printf_(), and translate_I2C_Error().
HAL_I2C_SlaveRxCpltCallback()
void HAL_I2C_SlaveRxCpltCallback (I2C_HandleTypeDef * hi2c)
Definition at line 111 of file heartrateReceiver.c.
References first, flagErrorHandler(), halStatusHandler(), heartrate_ram, heartrate_rx_offset, hrReceiverThreadId, I2C_EVENT, newLine, printf_(), and translate_I2C_Error().
HAL_I2C_SlaveTxCpltCallback()
void HAL_I2C_SlaveTxCpltCallback (I2C_HandleTypeDef * hi2c)
Definition at line 168 of file heartrateReceiver.c.
References newLine, and printf_().
HrReceiver()
void HrReceiver (void * argument)
Main task for this module.
Parameters
argument ... provide hrReceiver_module_t for module behaviour change
Definition at line 244 of file heartrateReceiver.c.
References flagErrorHandler(), hrReceiver_failureHandler(), hrReceiver_handle_heartrate(), HRRECEIVER_RETVAL, I2C_EVENT, newLine, and printf_().
hrReceiver_failureHandler()
bool hrReceiver_failureHandler (HRRECEIVER_RETVAL value)
handles errors from console module functions. Serves as an error-handling wrapper for conditions
Parameters
value ... return value of any HRRECEIVER module function
Returns
true on failure values, false on successful values
Definition at line 310 of file heartrateReceiver.c.
References HRRECEIVER_FAILED, HRRECEIVER_INIT_ERROR, HRRECEIVER_OK, HRRECEIVER_RESOURCE_ERROR, newLine, and printf_().
hrReceiver_handle_heartrate()
HRRECEIVER_RETVAL hrReceiver_handle_heartrate ()
On I2C_EVENT signal, processes the heartrate values.
Note
There currently isn't any processing necessary, but the function can output debug functionality
Returns
either error or status macros, HRRECEIVER_OK on success
Definition at line 264 of file heartrateReceiver.c.
References heartrate_ram, HEARTRATE_RAM_SIZE, HRRECEIVER_OK, newLine, and printf_().
hrReceiver_i2c_callback()
void hrReceiver_i2c_callback ()
Definition at line 276 of file heartrateReceiver.c.
References newLine, and printf_().
hrReceiver_prep_peripherals()
HRRECEIVER_RETVAL hrReceiver_prep_peripherals ()
Prepares peripherals used in this module. Module fails to function without it.
Returns
either error or status macros, HRRECEIVER_OK on success
Definition at line 280 of file heartrateReceiver.c.
References halStatusHandler(), heartrate_ram, hi2c3, HRRECEIVER_OK, HRRECEIVER_RESOURCE_ERROR, printf_(), and translate_I2C_Error().
StartHrReceiver()
void StartHrReceiver (void * argument)
An initialization task for this module.
Parameters
argument ... provide hrReceiver_module_t for module behaviour change
Definition at line 228 of file heartrateReceiver.c.
References HrReceiver(), hrReceiver_attr, hrReceiver_failureHandler(), hrReceiver_prep_peripherals(), HRRECEIVER_RETVAL, hrReceiverThreadId, newLine, newValue, osStatusHandler(), printf_(), and selfSendTimer.
Variable Documentation
first
bool first = true
Definition at line 48 of file heartrateReceiver.c.
heartrate_ram
uint8_t heartrate_ram[HEARTRATE_RAM_SIZE]
Definition at line 172 of file application.c.
heartrate_rx_offset
uint8_t heartrate_rx_offset
Definition at line 173 of file application.c.
hrReceiver_attr
osThreadAttr_t hrReceiver_attr
Definition at line 164 of file application.c.
hrReceiverThreadId
osThreadId_t hrReceiverThreadId
Definition at line 161 of file application.c.
i2cSem
osSemaphoreId_t i2cSem
Definition at line 198 of file application.c.
newLine
const char* newLine
Definition at line 19 of file application.c.
newValue
uint8_t newValue = 0
Definition at line 49 of file heartrateReceiver.c.
selfAddress_read
uint8_t selfAddress_read = (0x69 << 1) | 1
Definition at line 51 of file heartrateReceiver.c.
selfAddress_write
uint8_t selfAddress_write = (0x69 << 1)
Definition at line 50 of file heartrateReceiver.c.
selfSendTimer
osTimerId_t selfSendTimer
Definition at line 47 of file heartrateReceiver.c.