Project DreamTeam: Core/Inc/helper.h File Reference
helper.h File Reference
#include "stm32l4xx_hal.h"
#include "stdbool.h"
#include "cmsis_os2.h"
#include "printf.h"
#include "stm32l4xx_ll_usart.h"
#include "stm32l4xx_ll_i2c.h"
Functions
bool flagErrorHandler (uint32_t flag)
checks provided flag for osFlagsErrors
bool threadErrorHandler (osThreadId_t id, char *msg)
checks provided thread id for null
bool halStatusHandler (HAL_StatusTypeDef val)
checks the provided HAL status for errors
bool osStatusHandler (osStatus_t val)
checks the provided OS status for errors
void translate_I2C_Error (I2C_HandleTypeDef *hi2c)
translates and outputs the error message for I2C errors
void translate_UART_Error (UART_HandleTypeDef *huart)
translates and outputs the error message for UART errors
void printDebug (const char *msg)
outputs a debug message (used for debugging purposes)
Function Documentation
flagErrorHandler()
bool flagErrorHandler (uint32_t flag)
checks provided flag for osFlagsErrors
Note
This is only to be used for flag functions in CMSIS
Parameters
flag ... return value of osFlag function
Returns
true on failure, false on success
Definition at line 13 of file helper.c.
References printDebug().
halStatusHandler()
bool halStatusHandler (HAL_StatusTypeDef val)
checks the provided HAL status for errors
Note
This is typically used after a HAL operation to ensure its success
Parameters
val ... return value of a HAL operation
Returns
true on failure, false on success
Definition at line 51 of file helper.c.
References printDebug().
osStatusHandler()
bool osStatusHandler (osStatus_t val)
checks the provided OS status for errors
Note
This is typically used after an os operation to ensure its success
Parameters
val ... return value of an os operation
Returns
true on failure, false on success
Definition at line 71 of file helper.c.
References printDebug().
printDebug()
void printDebug (const char * msg)
outputs a debug message (used for debugging purposes)
Note
If DEBUG is not defined, function content will not be compiled and no output occurs
Parameters
msg ... arbitrary message string to output
Definition at line 180 of file helper.c.
References printf_().
threadErrorHandler()
bool threadErrorHandler (osThreadId_t id, char * msg)
checks provided thread id for null
Parameters
id ... osThreadId of created thread
msg ... name of thread or any other arbitrary message
Returns
true on failure, false on success
Definition at line 43 of file helper.c.
References printf_().
translate_I2C_Error()
void translate_I2C_Error (I2C_HandleTypeDef * hi2c)
translates and outputs the error message for I2C errors
Note
This is typically used for debugging purposes
Parameters
hi2c ... pointer to a I2C_HandleTypeDef structure that contains the configuration information for I2C module.
Definition at line 106 of file helper.c.
References printf_().
translate_UART_Error()
void translate_UART_Error (UART_HandleTypeDef * huart)
translates and outputs the error message for UART errors
Note
This is typically used for debugging purposes
Parameters
huart ... pointer to a UART_HandleTypeDef structure that contains the configuration information for UART module.
Definition at line 148 of file helper.c.
References printf_().