Project DreamTeam: Core/Src/parser.c File Reference
parser.c File Reference
#include "parser.h"
Functions
void StartParser (void *argument)
An initialization task for this module.
void Parser (void *argument)
Main task for this module.
PARSER_RETVAL parser_handle_input ()
On NEW_INPUT signal, parses given input and notifies WIFIBLE module.
PARSER_RETVAL parser_handle_message ()
On NEW_MESSAGE signal, parses given newMsg and notifies WIFIBLE module.
PARSER_RETVAL parser_handle_copyReattempt ()
On COPY_REATTEMPT signal, rethrows notification to WIFIBLE module for re-attempting.
PARSER_RETVAL parser_parseInput ()
Parses the global variable 'input'.
PARSER_RETVAL parser_parseMessage ()
Parses the global variable 'newMsg'.
bool parser_failureHandler (PARSER_RETVAL value)
Handles errors from parser module functions. Serves as an error-handling wrapper for conditions.
Variables
const char * newLine
osThreadId_t parserThreadId
const osThreadAttr_t parser_attr
osThreadId_t wifibleThreadId
osThreadId_t consoleThreadId
osThreadId_t webserverThreadId
osSemaphoreId_t inputSem
char * input
osSemaphoreId_t msgSem
char * newMsg
uint8_t responseLink
osSemaphoreId_t httpSem
char * http_data
uint8_t clients [4]
uint8_t requestType
Function Documentation
Parser()
void Parser (void * argument)
Main task for this module.
Parameters
argument ... provide parser_module_t for module behaviour change
Definition at line 46 of file parser.c.
References COPY_REATTEMPT, flagErrorHandler(), MSG_EVENT, NEW_INPUT, newLine, parser_failureHandler(), parser_handle_copyReattempt(), parser_handle_input(), parser_handle_message(), PARSER_RETVAL, and printf_().
parser_failureHandler()
bool parser_failureHandler (PARSER_RETVAL value)
Handles errors from parser module functions. Serves as an error-handling wrapper for conditions.
Parameters
value ... return value of any PARSER module function
Returns
true on failure values, false on successful values
Definition at line 297 of file parser.c.
References newLine, PARSER_DATA_ERROR, PARSER_FAILED, PARSER_FAILED_SEMAPHORE, PARSER_INIT_ERROR, PARSER_MEM_ERROR, PARSER_NEW_REQUEST, PARSER_OK, PARSER_RESERVED_ERROR, PARSER_RESOURCE_ERROR, and printf_().
parser_handle_copyReattempt()
PARSER_RETVAL parser_handle_copyReattempt ()
On COPY_REATTEMPT signal, rethrows notification to WIFIBLE module for re-attempting.
Note
Not fully implemented, but was supposed to handle reattempt on SEMAPHORE errors when copying data into global
Returns
either error or status macros, PARSER_OK on success
Definition at line 133 of file parser.c.
References COPY_REATTEMPT, flagErrorHandler(), PARSER_FAILED, PARSER_OK, and wifibleThreadId.
parser_handle_input()
PARSER_RETVAL parser_handle_input ()
On NEW_INPUT signal, parses given input and notifies WIFIBLE module.
Returns
either error or status macros, PARSER_OK on success
Definition at line 79 of file parser.c.
References acquire_semaphore(), flagErrorHandler(), inputSem, MODULE_SEM_TIMEOUT, PARSER_FAILED, PARSER_OK, parser_parseInput(), PARSER_RETVAL, release_semaphore(), USER_INPUT, and wifibleThreadId.
parser_handle_message()
PARSER_RETVAL parser_handle_message ()
On NEW_MESSAGE signal, parses given newMsg and notifies WIFIBLE module.
Note
Behaviour varies, depending on message received
Returns
either error or status macros, PARSER_OK on success
Definition at line 104 of file parser.c.
References acquire_semaphore(), flagErrorHandler(), MODULE_SEM_TIMEOUT, msgSem, NEW_REQUEST, NEW_RESPONSE, PARSER_DATA_ERROR, PARSER_FAILED, parser_failureHandler(), PARSER_NEW_REQUEST, PARSER_OK, parser_parseMessage(), PARSER_RETVAL, webserverThreadId, and wifibleThreadId.
parser_parseInput()
PARSER_RETVAL parser_parseInput ()
Parses the global variable 'input'.
Returns
either error or status macros, PARSER_OK on success
Definition at line 141 of file parser.c.
References input, newLine, PARSER_OK, and printf_().
parser_parseMessage()
PARSER_RETVAL parser_parseMessage ()
Parses the global variable 'newMsg'.
Returns
either error or status macros, PARSER_OK on success
Definition at line 148 of file parser.c.
References acquire_semaphore(), APPLICATION_OK, CLIENT_CLOSED, CLIENT_CONNECTED, CLIENT_FAILED, clients, HTML_REQUEST, httpSem, JSON_REQUEST, MODULE_SEM_TIMEOUT, msgSem, newLine, newMsg, PARSER_DATA_ERROR, PARSER_NEW_REQUEST, PARSER_OK, PARSER_RETVAL, printf_(), release_semaphore(), request_buffer, requestType, and responseLink.
StartParser()
void StartParser (void * argument)
An initialization task for this module.
Parameters
argument ... provide parser_module_t for module behaviour change
Definition at line 40 of file parser.c.
References Parser(), parser_attr, and parserThreadId.
Variable Documentation
clients
uint8_t clients[4]
Definition at line 90 of file application.c.
consoleThreadId
osThreadId_t consoleThreadId
Definition at line 108 of file application.c.
http_data
char* http_data
httpSem
osSemaphoreId_t httpSem
Definition at line 191 of file application.c.
input
char* input
Definition at line 122 of file application.c.
inputSem
osSemaphoreId_t inputSem
Definition at line 177 of file application.c.
msgSem
osSemaphoreId_t msgSem
Definition at line 184 of file application.c.
newLine
const char* newLine
Definition at line 19 of file application.c.
newMsg
char* newMsg
Definition at line 86 of file application.c.
parser_attr
const osThreadAttr_t parser_attr
Definition at line 34 of file application.c.
parserThreadId
osThreadId_t parserThreadId
Definition at line 31 of file application.c.
requestType
uint8_t requestType
Definition at line 88 of file application.c.
responseLink
uint8_t responseLink
Definition at line 87 of file application.c.
webserverThreadId
osThreadId_t webserverThreadId
wifibleThreadId
osThreadId_t wifibleThreadId
Definition at line 74 of file application.c.