Project DreamTeam: Core/Inc/parser.h File Reference
parser.h File Reference
#include "application.h"
#include "FreeRTOS.h"
#include "cmsis_os2.h"
#include "usart.h"
#include "printf.h"
#include "string.h"
#include "helper.h"
#include "stdbool.h"
#include "stdio.h"
Data Structures
struct parser_module
A structure to provide flags for behaviour change of the module.
Macros
#define PARSER_MODULE_STACK_SIZE 512
#define PARSER_REQUEST_BUFFER_SIZE 256
#define PARSER_RESPONSE_BUFFER_SIZE 256
#define PARSER_MODULE_NAME "PARSER"
#define PARSER_MODULE_INIT_NAME "ParserInit"
#define PARSER_RETVAL uint8_t
#define PARSER_OK APPLICATION_OK
#define PARSER_FAILED 0x01
#define PARSER_FAILED_SEMAPHORE 0x02
#define PARSER_NEW_REQUEST 0x04
#define PARSER_NOT_IMPLEMENTED 0xFA
#define PARSER_MEM_ERROR 0xFB
#define PARSER_RESERVED_ERROR 0xFC
#define PARSER_DATA_ERROR 0xFD
#define PARSER_RESOURCE_ERROR 0xFE
#define PARSER_INIT_ERROR 0xFF
Typedefs
typedef struct parser_module parser_module_t
A structure to provide flags for behaviour change of the module.
Functions
void StartParser (void *argument)
An initialization task for this module.
void Parser (void *argument)
Main task for this module.
PARSER_RETVAL parser_handle_input ()
On NEW_INPUT signal, parses given input and notifies WIFIBLE module.
PARSER_RETVAL parser_handle_message ()
On NEW_MESSAGE signal, parses given newMsg and notifies WIFIBLE module.
PARSER_RETVAL parser_handle_copyReattempt ()
On COPY_REATTEMPT signal, rethrows notification to WIFIBLE module for re-attempting.
PARSER_RETVAL parser_parseInput ()
Parses the global variable 'input'.
PARSER_RETVAL parser_parseMessage ()
Parses the global variable 'newMsg'.
bool parser_failureHandler (PARSER_RETVAL value)
Handles errors from parser module functions. Serves as an error-handling wrapper for conditions.
Macro Definition Documentation
PARSER_DATA_ERROR
#define PARSER_DATA_ERROR 0xFD
Definition at line 40 of file parser.h.
PARSER_FAILED
#define PARSER_FAILED 0x01
Definition at line 33 of file parser.h.
PARSER_FAILED_SEMAPHORE
#define PARSER_FAILED_SEMAPHORE 0x02
Definition at line 34 of file parser.h.
PARSER_INIT_ERROR
#define PARSER_INIT_ERROR 0xFF
Definition at line 42 of file parser.h.
PARSER_MEM_ERROR
#define PARSER_MEM_ERROR 0xFB
Definition at line 38 of file parser.h.
PARSER_MODULE_INIT_NAME
#define PARSER_MODULE_INIT_NAME "ParserInit"
Definition at line 29 of file parser.h.
PARSER_MODULE_NAME
#define PARSER_MODULE_NAME "PARSER"
Definition at line 28 of file parser.h.
PARSER_MODULE_STACK_SIZE
#define PARSER_MODULE_STACK_SIZE 512
Definition at line 25 of file parser.h.
PARSER_NEW_REQUEST
#define PARSER_NEW_REQUEST 0x04
Definition at line 35 of file parser.h.
PARSER_NOT_IMPLEMENTED
#define PARSER_NOT_IMPLEMENTED 0xFA
Definition at line 37 of file parser.h.
PARSER_OK
#define PARSER_OK APPLICATION_OK
Definition at line 32 of file parser.h.
PARSER_REQUEST_BUFFER_SIZE
#define PARSER_REQUEST_BUFFER_SIZE 256
Definition at line 26 of file parser.h.
PARSER_RESERVED_ERROR
#define PARSER_RESERVED_ERROR 0xFC
Definition at line 39 of file parser.h.
PARSER_RESOURCE_ERROR
#define PARSER_RESOURCE_ERROR 0xFE
Definition at line 41 of file parser.h.
PARSER_RESPONSE_BUFFER_SIZE
#define PARSER_RESPONSE_BUFFER_SIZE 256
Definition at line 27 of file parser.h.
PARSER_RETVAL
#define PARSER_RETVAL uint8_t
Definition at line 30 of file parser.h.
Typedef Documentation
parser_module_t
typedef struct parser_module parser_module_t
A structure to provide flags for behaviour change of the module.
Note
Currently there are no behaviour changes implemented.
Function Documentation
Parser()
void Parser (void * argument)
Main task for this module.
Parameters
argument ... provide parser_module_t for module behaviour change
Definition at line 46 of file parser.c.
References COPY_REATTEMPT, flagErrorHandler(), MSG_EVENT, NEW_INPUT, newLine, parser_failureHandler(), parser_handle_copyReattempt(), parser_handle_input(), parser_handle_message(), PARSER_RETVAL, and printf_().
parser_failureHandler()
bool parser_failureHandler (PARSER_RETVAL value)
Handles errors from parser module functions. Serves as an error-handling wrapper for conditions.
Parameters
value ... return value of any PARSER module function
Returns
true on failure values, false on successful values
Definition at line 297 of file parser.c.
References newLine, PARSER_DATA_ERROR, PARSER_FAILED, PARSER_FAILED_SEMAPHORE, PARSER_INIT_ERROR, PARSER_MEM_ERROR, PARSER_NEW_REQUEST, PARSER_OK, PARSER_RESERVED_ERROR, PARSER_RESOURCE_ERROR, and printf_().
parser_handle_copyReattempt()
PARSER_RETVAL parser_handle_copyReattempt ()
On COPY_REATTEMPT signal, rethrows notification to WIFIBLE module for re-attempting.
Note
Not fully implemented, but was supposed to handle reattempt on SEMAPHORE errors when copying data into global
Returns
either error or status macros, PARSER_OK on success
Definition at line 133 of file parser.c.
References COPY_REATTEMPT, flagErrorHandler(), PARSER_FAILED, PARSER_OK, and wifibleThreadId.
parser_handle_input()
PARSER_RETVAL parser_handle_input ()
On NEW_INPUT signal, parses given input and notifies WIFIBLE module.
Returns
either error or status macros, PARSER_OK on success
Definition at line 79 of file parser.c.
References acquire_semaphore(), flagErrorHandler(), inputSem, MODULE_SEM_TIMEOUT, PARSER_FAILED, PARSER_OK, parser_parseInput(), PARSER_RETVAL, release_semaphore(), USER_INPUT, and wifibleThreadId.
parser_handle_message()
PARSER_RETVAL parser_handle_message ()
On NEW_MESSAGE signal, parses given newMsg and notifies WIFIBLE module.
Note
Behaviour varies, depending on message received
Returns
either error or status macros, PARSER_OK on success
Definition at line 104 of file parser.c.
References acquire_semaphore(), flagErrorHandler(), MODULE_SEM_TIMEOUT, msgSem, NEW_REQUEST, NEW_RESPONSE, PARSER_DATA_ERROR, PARSER_FAILED, parser_failureHandler(), PARSER_NEW_REQUEST, PARSER_OK, parser_parseMessage(), PARSER_RETVAL, webserverThreadId, and wifibleThreadId.
parser_parseInput()
PARSER_RETVAL parser_parseInput ()
Parses the global variable 'input'.
Returns
either error or status macros, PARSER_OK on success
Definition at line 141 of file parser.c.
References input, newLine, PARSER_OK, and printf_().
parser_parseMessage()
PARSER_RETVAL parser_parseMessage ()
Parses the global variable 'newMsg'.
Returns
either error or status macros, PARSER_OK on success
Definition at line 148 of file parser.c.
References acquire_semaphore(), APPLICATION_OK, CLIENT_CLOSED, CLIENT_CONNECTED, CLIENT_FAILED, clients, HTML_REQUEST, httpSem, JSON_REQUEST, MODULE_SEM_TIMEOUT, msgSem, newLine, newMsg, PARSER_DATA_ERROR, PARSER_NEW_REQUEST, PARSER_OK, PARSER_RETVAL, printf_(), release_semaphore(), request_buffer, requestType, and responseLink.
StartParser()
void StartParser (void * argument)
An initialization task for this module.
Parameters
argument ... provide parser_module_t for module behaviour change
Definition at line 40 of file parser.c.
References Parser(), parser_attr, and parserThreadId.