Project DreamTeam: Core/Src/usart.c File Reference
usart.c File Reference
This file provides code for the configuration of the USART instances.
#include "usart.h"
Functions
void MX_USART1_UART_Init (void)
void MX_USART2_UART_Init (void)
void HAL_UART_MspInit (UART_HandleTypeDef *uartHandle)
void HAL_UART_MspDeInit (UART_HandleTypeDef *uartHandle)
void usart_idle_handler (UART_HandleTypeDef *uartHandle, osThreadId_t notifyTaskId)
void putchar_ (char character)
Variables
UART_HandleTypeDef huart1
UART_HandleTypeDef huart2
DMA_HandleTypeDef hdma_usart1_rx
DMA_HandleTypeDef hdma_usart1_tx
DMA_HandleTypeDef hdma_usart2_tx
Detailed Description
This file provides code for the configuration of the USART instances.
Attention
Copyright (c) 2023 STMicroelectronics. All rights reserved.
This software is licensed under terms that can be found in the LICENSE file in the root directory of this software component. If no LICENSE file comes with this software, it is provided AS-IS.
Definition in file usart.c.
Function Documentation
HAL_UART_MspDeInit()
void HAL_UART_MspDeInit (UART_HandleTypeDef * uartHandle)
USART1 GPIO Configuration PA9 ---—> USART1_TX PA10 ---—> USART1_RX
USART2 GPIO Configuration PA2 ---—> USART2_TX PA15 (JTDI) ---—> USART2_RX
Definition at line 237 of file usart.c.
References VCP_RX_Pin, and VCP_TX_Pin.
HAL_UART_MspInit()
void HAL_UART_MspInit (UART_HandleTypeDef * uartHandle)
Initializes the peripherals clock
USART1 GPIO Configuration PA9 ---—> USART1_TX PA10 ---—> USART1_RX
Initializes the peripherals clock
USART2 GPIO Configuration PA2 ---—> USART2_TX PA15 (JTDI) ---—> USART2_RX
Definition at line 96 of file usart.c.
References Error_Handler(), hdma_usart1_rx, hdma_usart1_tx, hdma_usart2_tx, VCP_RX_GPIO_Port, VCP_RX_Pin, VCP_TX_GPIO_Port, and VCP_TX_Pin.
MX_USART1_UART_Init()
void MX_USART1_UART_Init (void)
Definition at line 35 of file usart.c.
References Error_Handler(), and huart1.
MX_USART2_UART_Init()
void MX_USART2_UART_Init (void)
Definition at line 66 of file usart.c.
References Error_Handler(), and huart2.
putchar_()
void putchar_ (char c)
Prints/send a single character to some opaque output entity
Note
This function is not implemented by the library, only declared; you must provide an implementation if you wish to use the printf / vprintf function (and possibly for linking against the library, if your toolchain does not support discarding unused functions)
The output could be as simple as a wrapper for the write() system call on a Unix-like system, or even libc's putchar , for replicating actual functionality of libc's printf function; but on an embedded system it may involve interaction with a special output device, like a UART, etc.
in libc's putchar, the parameter type is an int; this was intended to support the representation of either a proper character or EOF in a variable - but this is really not meaningful to pass into putchar and is discouraged today. See further discussion in: c the single character to print
Definition at line 306 of file usart.c.
References huart2.
usart_idle_handler()
void usart_idle_handler (UART_HandleTypeDef * uartHandle, osThreadId_t notifyTaskId)
Definition at line 290 of file usart.c.
References flagErrorHandler(), and USART_IDLE_EVENT.
Variable Documentation
hdma_usart1_rx
DMA_HandleTypeDef hdma_usart1_rx
Definition at line 29 of file usart.c.
hdma_usart1_tx
DMA_HandleTypeDef hdma_usart1_tx
Definition at line 30 of file usart.c.
hdma_usart2_tx
DMA_HandleTypeDef hdma_usart2_tx
Definition at line 31 of file usart.c.
huart1
UART_HandleTypeDef huart1
Definition at line 27 of file usart.c.
huart2
UART_HandleTypeDef huart2
Definition at line 28 of file usart.c.