Project DreamTeam: Core/Inc/webserver.h File Reference
webserver.h File Reference
#include "application.h"
#include "FreeRTOS.h"
#include "cmsis_os2.h"
#include "stdbool.h"
#include "printf.h"
#include "string.h"
#include "helper.h"
#include "picohttpparser.h"
Data Structures
struct webserver_module
A structure to provide flags for behaviour change of the module.
struct client
Structure to represent client details.
struct requestPacket
Structure to represent request packet details.
struct responsePacket
Structure to represent response packet details.
Macros
#define INC_WEBSERVER_H_
THIS MODULE IS NOT USED IN THE PROJECT, PLEASE IGNORE.
#define WEBSERVER_MODULE_STACK_SIZE 256
#define WEBSERVER_MODULE_NAME "WEBSERVER"
#define WEBSERVER_MODULE_INIT_NAME "WebserverInit"
#define WEBSERVER_MODULE_SERVER_NAME "Webserver"
#define WEBSERVER_RETVAL uint8_t
#define WEBSERVER_MAX_CONNECTIONS 2U
#define WEBSERVER_MAX_HANDLE_QUEUE 10U
#define GET_REQUEST "GET"
#define WEBSERVER_OK 0x00
#define WEBSERVER_FAILED_COPY 0x01
#define WEBSERVER_FAILED_SEMAPHORE 0x02
#define WEBSERVER_FAILED_FLAG 0x04
#define WEBSERVER_FAILED_QUEUE 0x08
#define WEBSERVER_NOT_IMPLEMENTED 0xFA
#define WEBSERVER_MEM_ERROR 0xFB
#define WEBSERVER_CONNECTION_ERROR 0xFC
#define WEBSERVER_REQUEST_ERROR 0xFD
#define WEBSERVER_UNKOWN_ERROR 0xFE
#define WEBSERVER_INIT_ERROR 0xFF
Typedefs
typedef struct webserver_module webserver_module_t
A structure to provide flags for behaviour change of the module.
typedef struct client client_t
Structure to represent client details.
typedef struct requestPacket requestPacket_t
Structure to represent request packet details.
typedef struct responsePacket responsePacket_t
Structure to represent response packet details.
Functions
void StartWebserverModule (void *argument)
An initialization task for this module.
void Webserver (void *argument)
Main task for this module.
WEBSERVER_RETVAL webserver_handle_connection ()
Handles a new web server connection.
WEBSERVER_RETVAL webserver_handle_request ()
Handles a new web server request.
bool webserver_failureHandler (WEBSERVER_RETVAL value)
Handles errors from webserver module functions. Serves as an error-handling wrapper for conditions.
Macro Definition Documentation
GET_REQUEST
#define GET_REQUEST "GET"
Definition at line 37 of file webserver.h.
INC_WEBSERVER_H_
#define INC_WEBSERVER_H_
THIS MODULE IS NOT USED IN THE PROJECT, PLEASE IGNORE.
Note
It was my failed attempt to use libraries, which would do server operations
I failed to find a suitable and small enough library. Time was lacking and so I dropped it.
Definition at line 15 of file webserver.h.
WEBSERVER_CONNECTION_ERROR
#define WEBSERVER_CONNECTION_ERROR 0xFC
Definition at line 47 of file webserver.h.
WEBSERVER_FAILED_COPY
#define WEBSERVER_FAILED_COPY 0x01
Definition at line 40 of file webserver.h.
WEBSERVER_FAILED_FLAG
#define WEBSERVER_FAILED_FLAG 0x04
Definition at line 42 of file webserver.h.
WEBSERVER_FAILED_QUEUE
#define WEBSERVER_FAILED_QUEUE 0x08
Definition at line 43 of file webserver.h.
WEBSERVER_FAILED_SEMAPHORE
#define WEBSERVER_FAILED_SEMAPHORE 0x02
Definition at line 41 of file webserver.h.
WEBSERVER_INIT_ERROR
#define WEBSERVER_INIT_ERROR 0xFF
Definition at line 50 of file webserver.h.
WEBSERVER_MAX_CONNECTIONS
#define WEBSERVER_MAX_CONNECTIONS 2U
Definition at line 34 of file webserver.h.
WEBSERVER_MAX_HANDLE_QUEUE
#define WEBSERVER_MAX_HANDLE_QUEUE 10U
Definition at line 35 of file webserver.h.
WEBSERVER_MEM_ERROR
#define WEBSERVER_MEM_ERROR 0xFB
Definition at line 46 of file webserver.h.
WEBSERVER_MODULE_INIT_NAME
#define WEBSERVER_MODULE_INIT_NAME "WebserverInit"
Definition at line 31 of file webserver.h.
WEBSERVER_MODULE_NAME
#define WEBSERVER_MODULE_NAME "WEBSERVER"
Definition at line 30 of file webserver.h.
WEBSERVER_MODULE_SERVER_NAME
#define WEBSERVER_MODULE_SERVER_NAME "Webserver"
Definition at line 32 of file webserver.h.
WEBSERVER_MODULE_STACK_SIZE
#define WEBSERVER_MODULE_STACK_SIZE 256
Definition at line 29 of file webserver.h.
WEBSERVER_NOT_IMPLEMENTED
#define WEBSERVER_NOT_IMPLEMENTED 0xFA
Definition at line 45 of file webserver.h.
WEBSERVER_OK
#define WEBSERVER_OK 0x00
Definition at line 39 of file webserver.h.
WEBSERVER_REQUEST_ERROR
#define WEBSERVER_REQUEST_ERROR 0xFD
Definition at line 48 of file webserver.h.
WEBSERVER_RETVAL
#define WEBSERVER_RETVAL uint8_t
Definition at line 33 of file webserver.h.
WEBSERVER_UNKOWN_ERROR
#define WEBSERVER_UNKOWN_ERROR 0xFE
Definition at line 49 of file webserver.h.
Typedef Documentation
client_t
typedef struct client client_t
Structure to represent client details.
requestPacket_t
typedef struct requestPacket requestPacket_t
Structure to represent request packet details.
responsePacket_t
typedef struct responsePacket responsePacket_t
Structure to represent response packet details.
webserver_module_t
typedef struct webserver_module webserver_module_t
A structure to provide flags for behaviour change of the module.
Note
Specify which flags will affect the behavior of the module.
Function Documentation
StartWebserverModule()
void StartWebserverModule (void * argument)
An initialization task for this module.
Parameters
argument ... provide webserver_module_t for module behaviour change
Definition at line 40 of file webserver.c.
References Webserver(), webserver_attr, and webserverThreadId.
Webserver()
void Webserver (void * argument)
Main task for this module.
Parameters
argument ... provide webserver_module_t for module behaviour change
Definition at line 46 of file webserver.c.
References flagErrorHandler(), NEW_CONNECTION, NEW_REQUEST, newLine, printf_(), webserver_failureHandler(), webserver_handle_connection(), webserver_handle_request(), and WEBSERVER_RETVAL.
webserver_failureHandler()
bool webserver_failureHandler (WEBSERVER_RETVAL value)
Handles errors from webserver module functions. Serves as an error-handling wrapper for conditions.
Parameters
value ... return value of any WEBSERVER module function
Returns
true on failure values, false on successful values
Definition at line 81 of file webserver.c.
References newLine, printf_(), WEBSERVER_CONNECTION_ERROR, WEBSERVER_FAILED_COPY, WEBSERVER_FAILED_FLAG, WEBSERVER_FAILED_QUEUE, WEBSERVER_FAILED_SEMAPHORE, WEBSERVER_INIT_ERROR, WEBSERVER_MEM_ERROR, WEBSERVER_OK, WEBSERVER_REQUEST_ERROR, and WEBSERVER_UNKOWN_ERROR.
webserver_handle_connection()
WEBSERVER_RETVAL webserver_handle_connection ()
Handles a new web server connection.
Returns
either error or status macros, WEBSERVER_OK on success
Definition at line 73 of file webserver.c.
References WEBSERVER_NOT_IMPLEMENTED.
webserver_handle_request()
WEBSERVER_RETVAL webserver_handle_request ()
Handles a new web server request.
Returns
either error or status macros, WEBSERVER_OK on success
Definition at line 77 of file webserver.c.
References WEBSERVER_NOT_IMPLEMENTED.