Project DreamTeam: Core/Src/webserver.c File Reference
webserver.c File Reference
#include "webserver.h"
Functions
void StartWebserverModule (void *argument)
An initialization task for this module.
void Webserver (void *argument)
Main task for this module.
WEBSERVER_RETVAL webserver_handle_connection ()
Handles a new web server connection.
WEBSERVER_RETVAL webserver_handle_request ()
Handles a new web server request.
bool webserver_failureHandler (WEBSERVER_RETVAL value)
Handles errors from webserver module functions. Serves as an error-handling wrapper for conditions.
Variables
const char * newLine
osThreadId_t webserverThreadId
const osThreadAttr_t webserver_attr
osThreadId_t parserThreadId
osSemaphoreId_t httpSem
char * http_data
Function Documentation
StartWebserverModule()
void StartWebserverModule (void * argument)
An initialization task for this module.
Parameters
argument ... provide webserver_module_t for module behaviour change
Definition at line 40 of file webserver.c.
References Webserver(), webserver_attr, and webserverThreadId.
Webserver()
void Webserver (void * argument)
Main task for this module.
Parameters
argument ... provide webserver_module_t for module behaviour change
Definition at line 46 of file webserver.c.
References flagErrorHandler(), NEW_CONNECTION, NEW_REQUEST, newLine, printf_(), webserver_failureHandler(), webserver_handle_connection(), webserver_handle_request(), and WEBSERVER_RETVAL.
webserver_failureHandler()
bool webserver_failureHandler (WEBSERVER_RETVAL value)
Handles errors from webserver module functions. Serves as an error-handling wrapper for conditions.
Parameters
value ... return value of any WEBSERVER module function
Returns
true on failure values, false on successful values
Definition at line 81 of file webserver.c.
References newLine, printf_(), WEBSERVER_CONNECTION_ERROR, WEBSERVER_FAILED_COPY, WEBSERVER_FAILED_FLAG, WEBSERVER_FAILED_QUEUE, WEBSERVER_FAILED_SEMAPHORE, WEBSERVER_INIT_ERROR, WEBSERVER_MEM_ERROR, WEBSERVER_OK, WEBSERVER_REQUEST_ERROR, and WEBSERVER_UNKOWN_ERROR.
webserver_handle_connection()
WEBSERVER_RETVAL webserver_handle_connection ()
Handles a new web server connection.
Returns
either error or status macros, WEBSERVER_OK on success
Definition at line 73 of file webserver.c.
References WEBSERVER_NOT_IMPLEMENTED.
webserver_handle_request()
WEBSERVER_RETVAL webserver_handle_request ()
Handles a new web server request.
Returns
either error or status macros, WEBSERVER_OK on success
Definition at line 77 of file webserver.c.
References WEBSERVER_NOT_IMPLEMENTED.
Variable Documentation
http_data
char* http_data
httpSem
osSemaphoreId_t httpSem
Definition at line 191 of file application.c.
newLine
const char* newLine
Definition at line 19 of file application.c.
parserThreadId
osThreadId_t parserThreadId
Definition at line 31 of file application.c.
webserver_attr
const osThreadAttr_t webserver_attr
webserverThreadId
osThreadId_t webserverThreadId