Project DreamTeam: Core/Src/wifi-ble.c File Reference
wifi-ble.c File Reference
#include "wifi-ble.h"
Functions
void HAL_UART_AbortCpltCallback (UART_HandleTypeDef *huart)
void HAL_UART_AbortReceiveCpltCallback (UART_HandleTypeDef *huart)
void StartWifiBleModule (void *argument)
An initialization task for this module.
void WifiReceiver (void *argument)
Task for handling Wi-Fi reception.
void BluetoothBeacon (void *argument)
Task for handling Bluetooth beacon.
wifible_wifi_cfg_t * wifible_wifi_default_cfg ()
Provides a default Wi-Fi configuration.
WIFIBLE_RETVAL wifible_wifi_clear_cfg (wifible_wifi_cfg_t *cfg)
Clears the provided Wi-Fi configuration.
WIFIBLE_RETVAL wifible_wifi_initialization (wifible_wifi_cfg_t *cfg)
Initializes the wifi module, using the provided configuration.
wifible_bt_cfg_t * wifible_bt_default_cfg ()
Provides a default Bluetooth configuration.
WIFIBLE_RETVAL wifible_bt_clear_cfg (wifible_bt_cfg_t *cfg)
Clears the provided Bluetooth configuration.
WIFIBLE_RETVAL wifible_bt_initialization (wifible_bt_cfg_t *cfg)
Initializes the bluetooth module, using the provided configuration.
WIFIBLE_RETVAL wifible_power_module (uint8_t power_state)
Powers the module on.
WIFIBLE_RETVAL wifible_handle_newData (size_t old_pos, size_t new_pos)
On IDLE_EVENT signal, checks uart1Buffer and decides copy-mechanism.
WIFIBLE_RETVAL wifible_enter_copy ()
enters the memory copy function and also clears previously allocated memory
WIFIBLE_RETVAL wifible_attempt_fullCopy (size_t start_pos, size_t length)
Copies data from uart1Buffer in 1 full step.
WIFIBLE_RETVAL wifible_attempt_partialCopy (size_t start_pos, size_t len1, size_t len2)
Copies data from uart1Buffer in 2 partial steps.
WIFIBLE_RETVAL wifible_handle_userInput ()
On USER_INPUT signal, forwards global 'input' variable to WIFIBLE over USART1.
WIFIBLE_RETVAL wifible_handle_newRequest ()
On NEW_REQUEST signal, responds to client via wifible_serve_webPage.
WIFIBLE_RETVAL wifible_serve_webPage (uint8_t link_id)
Serves a webpage or a JSON update to a client upon request over USART1.
void wifible_send_command (char *command, int length)
Sends the provided buffer to the WIFIBLE module.
void wifible_uart_receive_callback (UART_HandleTypeDef *huart)
void wifible_dma_receive_callback (DMA_HandleTypeDef *hdma)
WIFIBLE_RETVAL wifible_prep_peripherals ()
Prepares peripherals used in this module. Module fails to function without it.
bool wifible_failureHandler (WIFIBLE_RETVAL value)
Handles errors from wifible module functions. Serves as an error-handling wrapper for conditions.
Variables
const char * newLine
const char * HTTP_HEADER
const char * HTTP_CONTENT_TYPE_HTML
const char * HTTP_CONTENT_TYPE_TEXT
const char * HTTP_CONTENT_TYPE_JSON
const char * HTTP_CONTENT_LENGTH_TEMPLATE
const char * HTML_TEMPLATE
DMA_HandleTypeDef hdma_usart1_rx
osThreadId_t wifibleThreadId
const osThreadAttr_t wifible_attr
osThreadId_t wifibleReceiverThreadId
const osThreadAttr_t wifibleReceiver_attr
osThreadId_t parserThreadId
uint8_t uart1Buffer [WIFIBLE_UART_BUFFER_SIZE]
char * newMsg
osSemaphoreId_t msgSem
char * input
osSemaphoreId_t inputSem
uint8_t responseLink
osSemaphoreId_t i2cSem
uint8_t * heartrate_ram
uint8_t heartrate_read_index
uint8_t clients [4]
uint8_t requestType
char update [MAX_UPDATE_SIZE]
char update_response [MAX_UPDATE_SIZE]
char page [MAX_PAGE_SIZE]
char page_response [MAX_PAGE_SIZE]
uint16_t page_response_length
Function Documentation
BluetoothBeacon()
void BluetoothBeacon (void * argument)
Task for handling Bluetooth beacon.
Parameters
argument ... ignored / not used
Definition at line 162 of file wifi-ble.c.
References Error_Handler().
HAL_UART_AbortCpltCallback()
void HAL_UART_AbortCpltCallback (UART_HandleTypeDef * huart)
Definition at line 53 of file wifi-ble.c.
References newLine, and printf_().
HAL_UART_AbortReceiveCpltCallback()
void HAL_UART_AbortReceiveCpltCallback (UART_HandleTypeDef * huart)
Definition at line 59 of file wifi-ble.c.
References newLine, and printf_().
StartWifiBleModule()
void StartWifiBleModule (void * argument)
An initialization task for this module.
Parameters
argument ... provide wifible_module_t for module behaviour change
Definition at line 79 of file wifi-ble.c.
References BluetoothBeacon(), wifible_module::mode, wifible_attr, WIFIBLE_BLUETOOTH_MODE, wifible_bt_default_cfg(), wifible_bt_initialization(), wifible_prep_peripherals(), wifible_wifi_default_cfg(), wifible_wifi_initialization(), WIFIBLE_WIRELESS_MODE, wifibleThreadId, and WifiReceiver().
wifible_attempt_fullCopy()
WIFIBLE_RETVAL wifible_attempt_fullCopy (size_t start_pos, size_t length)
Copies data from uart1Buffer in 1 full step.
Parameters
start_pos ... the start position of the data to copy
length ... the length from start_pos to end of data
Returns
either error or status macros, WIFIBLE_OK on success
Definition at line 373 of file wifi-ble.c.
References flagErrorHandler(), MSG_EVENT, msgSem, newMsg, parserThreadId, release_semaphore(), uart1Buffer, wifible_enter_copy(), WIFIBLE_FAILED_FLAG, WIFIBLE_MEM_ERROR, WIFIBLE_OK, and WIFIBLE_RETVAL.
wifible_attempt_partialCopy()
WIFIBLE_RETVAL wifible_attempt_partialCopy (size_t start_pos, size_t len1, size_t len2)
Copies data from uart1Buffer in 2 partial steps.
Note
1st partial: start_pos to end of buffer using len1, 2nd partial: start of buffer to len2
Parameters
start_pos ... the start position of the data to copy
len1 ... the length from start to end of buffer
len2 ... the length from start of buffer to end of data
Returns
either error or status macros, WIFIBLE_OK on success
Definition at line 400 of file wifi-ble.c.
References flagErrorHandler(), MSG_EVENT, msgSem, newMsg, parserThreadId, release_semaphore(), uart1Buffer, wifible_enter_copy(), WIFIBLE_FAILED_FLAG, WIFIBLE_MEM_ERROR, WIFIBLE_OK, and WIFIBLE_RETVAL.
wifible_bt_clear_cfg()
WIFIBLE_RETVAL wifible_bt_clear_cfg (wifible_bt_cfg_t * cfg)
Clears the provided Bluetooth configuration.
Parameters
cfg ... pointer to a wifible_bt_cfg_t to be free'd from memory
Returns
either error or status macros, WIFIBLE_OK on success
Definition at line 291 of file wifi-ble.c.
References WIFIBLE_NOT_IMPLEMENTED.
wifible_bt_default_cfg()
wifible_bt_cfg_t* wifible_bt_default_cfg ()
Provides a default Bluetooth configuration.
Returns
a pointer to an allocated wifible_bt_cfg_t structure, which will be filled with default settings
Definition at line 287 of file wifi-ble.c.
wifible_bt_initialization()
WIFIBLE_RETVAL wifible_bt_initialization (wifible_bt_cfg_t * cfg)
Initializes the bluetooth module, using the provided configuration.
Parameters
cfg ... pointer to a wifible_bt_cfg_t to be used for configuration
Returns
either error or status macros, WIFIBLE_OK on success
Definition at line 295 of file wifi-ble.c.
References WIFIBLE_NOT_IMPLEMENTED.
wifible_dma_receive_callback()
void wifible_dma_receive_callback (DMA_HandleTypeDef * hdma)
Definition at line 526 of file wifi-ble.c.
References newLine, and printf_().
wifible_enter_copy()
WIFIBLE_RETVAL wifible_enter_copy ()
enters the memory copy function and also clears previously allocated memory
Returns
either error or status macros, WIFIBLE_OK on success
Definition at line 363 of file wifi-ble.c.
References acquire_semaphore(), MODULE_SEM_TIMEOUT, msgSem, newMsg, WIFIBLE_FAILED_COPY, and WIFIBLE_OK.
wifible_failureHandler()
bool wifible_failureHandler (WIFIBLE_RETVAL value)
Handles errors from wifible module functions. Serves as an error-handling wrapper for conditions.
Parameters
value ... return value of any WIFIBLE module function
Returns
true on failure values, false on successful values
Definition at line 551 of file wifi-ble.c.
References newLine, printf_(), WIFIBLE_FAILED_COPY, WIFIBLE_FAILED_FLAG, WIFIBLE_FAILED_SEMAPHORE, WIFIBLE_INIT_ERROR, WIFIBLE_MEM_ERROR, WIFIBLE_OK, WIFIBLE_POWER_ERROR, WIFIBLE_RESOURCE_ERROR, and WIFIBLE_RW_ERROR.
wifible_handle_newData()
WIFIBLE_RETVAL wifible_handle_newData (size_t old_pos, size_t new_pos)
On IDLE_EVENT signal, checks uart1Buffer and decides copy-mechanism.
Returns
either error or status macros, WIFIBLE_OK on success
Definition at line 304 of file wifi-ble.c.
References halStatusHandler(), huart2, printf_(), translate_UART_Error(), uart1Buffer, wifible_attempt_fullCopy(), wifible_attempt_partialCopy(), and WIFIBLE_UART_BUFFER_SIZE.
wifible_handle_newRequest()
WIFIBLE_RETVAL wifible_handle_newRequest ()
On NEW_REQUEST signal, responds to client via wifible_serve_webPage.
Returns
either error or status macros, WIFIBLE_OK on success
Definition at line 446 of file wifi-ble.c.
References responseLink, WIFIBLE_RETVAL, and wifible_serve_webPage().
wifible_handle_userInput()
WIFIBLE_RETVAL wifible_handle_userInput ()
On USER_INPUT signal, forwards global 'input' variable to WIFIBLE over USART1.
Returns
either error or status macros, WIFIBLE_OK on success
Definition at line 429 of file wifi-ble.c.
References acquire_semaphore(), AT_CMD_BUFFER_SIZE, at_execute_command(), input, inputSem, MODULE_SEM_TIMEOUT, release_semaphore(), WIFIBLE_OK, WIFIBLE_RETVAL, and wifible_send_command().
wifible_power_module()
WIFIBLE_RETVAL wifible_power_module (uint8_t power_state)
Powers the module on.
Note
Currently not implemented
Returns
either error or status macros, WIFIBLE_OK on success
Definition at line 299 of file wifi-ble.c.
References WIFIBLE_NOT_IMPLEMENTED.
wifible_prep_peripherals()
WIFIBLE_RETVAL wifible_prep_peripherals ()
Prepares peripherals used in this module. Module fails to function without it.
Returns
either error or status macros, WIFIBLE_OK on success
Definition at line 532 of file wifi-ble.c.
References halStatusHandler(), huart1, printf_(), translate_UART_Error(), uart1Buffer, WIFIBLE_OK, WIFIBLE_RESOURCE_ERROR, WIFIBLE_UART_BUFFER_SIZE, and wifible_uart_receive_callback().
wifible_send_command()
void wifible_send_command (char * command, int length)
Sends the provided buffer to the WIFIBLE module.
Note
This is a suitable callback function for the wrappers in ATcommands.c
Parameters
command ... buffer to be sent over USART1
length ... length of buffer
Returns
either error or status macros, WIFIBLE_OK on success
Definition at line 510 of file wifi-ble.c.
References halStatusHandler(), huart1, newLine, printf_(), and translate_UART_Error().
wifible_serve_webPage()
WIFIBLE_RETVAL wifible_serve_webPage (uint8_t link_id)
Serves a webpage or a JSON update to a client upon request over USART1.
Note
ALL connections will be dropped in this function, because programming is hard
Parameters
link_id ... connection link id of client
Returns
either error or status macros, WIFIBLE_OK on success
Definition at line 464 of file wifi-ble.c.
References AT_CMD_BUFFER_SIZE, AT_IP_CloseConnection, AT_IP_Send, at_set_command(), halStatusHandler(), heartrate_ram, HTTP_CONTENT_LENGTH_TEMPLATE, HTTP_CONTENT_TYPE_JSON, HTTP_HEADER, huart1, JSON_REQUEST, newLine, page_response, page_response_length, printf_(), requestType, sprintf_(), translate_UART_Error(), update, update_response, WIFIBLE_CMD_DELAY, WIFIBLE_OK, WIFIBLE_RW_ERROR, and wifible_send_command().
wifible_uart_receive_callback()
void wifible_uart_receive_callback (UART_HandleTypeDef * huart)
Definition at line 520 of file wifi-ble.c.
References newLine, and printf_().
wifible_wifi_clear_cfg()
WIFIBLE_RETVAL wifible_wifi_clear_cfg (wifible_wifi_cfg_t * cfg)
Clears the provided Wi-Fi configuration.
Parameters
cfg ... pointer to a wifible_wifi_cfg_t to be free'd from memory
Returns
either error or status macros, WIFIBLE_OK on success
Definition at line 212 of file wifi-ble.c.
References wifible_wifi_cfg::domain, wifible_wifi_cfg::hostname, wifible_wifi_cfg::local_gw, wifible_wifi_cfg::local_ip, wifible_wifi_cfg::local_netmask, wifible_wifi_cfg::pwd, wifible_wifi_cfg::ssid, and WIFIBLE_OK.
wifible_wifi_default_cfg()
wifible_wifi_cfg_t* wifible_wifi_default_cfg ()
Provides a default Wi-Fi configuration.
Returns
a pointer to an allocated wifible_wifi_cfg_t structure, which will be filled with default settings
Definition at line 168 of file wifi-ble.c.
References wifible_wifi_cfg::domain, wifible_wifi_cfg::hostname, HTML_TEMPLATE, HTTP_CONTENT_LENGTH_TEMPLATE, HTTP_CONTENT_TYPE_HTML, HTTP_HEADER, wifible_wifi_cfg::local_gw, wifible_wifi_cfg::local_ip, wifible_wifi_cfg::local_netmask, wifible_wifi_cfg::mode, page, page_response, page_response_length, wifible_wifi_cfg::pwd, SoftAP, sprintf_(), and wifible_wifi_cfg::ssid.
wifible_wifi_initialization()
WIFIBLE_RETVAL wifible_wifi_initialization (wifible_wifi_cfg_t * cfg)
Initializes the wifi module, using the provided configuration.
Parameters
cfg ... pointer to a wifible_wifi_cfg_t to be used for configuration
Returns
either error or status macros, WIFIBLE_OK on success
Definition at line 224 of file wifi-ble.c.
References AT_CMD_BUFFER_SIZE, AT_Disable, AT_Enable, at_execute_command(), AT_IP_ConnectionMode_Multiple, AT_IP_Server, AT_IP_Server_Create, AT_IP_Set_MultiConnectionMode, AT_IP_Set_SoftAP_IP, AT_IP_Set_SoftAP_MAC, at_query_command(), at_set_command(), AT_Startup, AT_Version, AT_WIFI_Enable_DHCP, AT_WIFI_Encryption_OPEN, AT_WIFI_MDNS, AT_WIFI_Set_DHCP_Range, AT_WIFI_Set_Hostname, AT_WIFI_Set_Mode, AT_WIFI_Set_SoftAP_Config, AT_WIFI_SoftAP_Mode, wifible_wifi_cfg::hostname, wifible_wifi_cfg::local_gw, wifible_wifi_cfg::local_ip, wifible_wifi_cfg::local_netmask, newLine, printf_(), wifible_wifi_cfg::pwd, wifible_wifi_cfg::ssid, WIFIBLE_CMD_DELAY, WIFIBLE_OK, and wifible_send_command().
WifiReceiver()
void WifiReceiver (void * argument)
Task for handling Wi-Fi reception.
Parameters
argument ... ignored / not used
Definition at line 106 of file wifi-ble.c.
References COPY_REATTEMPT, flagErrorHandler(), huart1, IDLE_EVENT, NEW_RESPONSE, newLine, parserThreadId, printf_(), USER_INPUT, WIFIBLE_FAILED_COPY, wifible_failureHandler(), wifible_handle_newData(), wifible_handle_newRequest(), wifible_handle_userInput(), WIFIBLE_RETVAL, and WIFIBLE_UART_BUFFER_SIZE.
Variable Documentation
clients
uint8_t clients[4]
Definition at line 90 of file application.c.
hdma_usart1_rx
DMA_HandleTypeDef hdma_usart1_rx
Definition at line 29 of file usart.c.
heartrate_ram
uint8_t* heartrate_ram
Definition at line 172 of file application.c.
heartrate_read_index
uint8_t heartrate_read_index
Definition at line 174 of file application.c.
HTML_TEMPLATE
const char* HTML_TEMPLATE
Definition at line 61 of file application.c.
HTTP_CONTENT_LENGTH_TEMPLATE
const char* HTTP_CONTENT_LENGTH_TEMPLATE
Definition at line 54 of file application.c.
HTTP_CONTENT_TYPE_HTML
const char* HTTP_CONTENT_TYPE_HTML
Definition at line 50 of file application.c.
HTTP_CONTENT_TYPE_JSON
const char* HTTP_CONTENT_TYPE_JSON
Definition at line 52 of file application.c.
HTTP_CONTENT_TYPE_TEXT
const char* HTTP_CONTENT_TYPE_TEXT
Definition at line 51 of file application.c.
HTTP_HEADER
const char* HTTP_HEADER
Definition at line 47 of file application.c.
i2cSem
osSemaphoreId_t i2cSem
Definition at line 198 of file application.c.
input
char* input
Definition at line 122 of file application.c.
inputSem
osSemaphoreId_t inputSem
Definition at line 177 of file application.c.
msgSem
osSemaphoreId_t msgSem
Definition at line 184 of file application.c.
newLine
const char* newLine
Definition at line 19 of file application.c.
newMsg
char* newMsg
Definition at line 86 of file application.c.
page
char page[MAX_PAGE_SIZE]
Definition at line 93 of file application.c.
page_response
char page_response[MAX_PAGE_SIZE]
Definition at line 94 of file application.c.
page_response_length
uint16_t page_response_length
Definition at line 95 of file application.c.
parserThreadId
osThreadId_t parserThreadId
Definition at line 31 of file application.c.
requestType
uint8_t requestType
Definition at line 88 of file application.c.
responseLink
uint8_t responseLink
Definition at line 87 of file application.c.
uart1Buffer
uint8_t uart1Buffer[WIFIBLE_UART_BUFFER_SIZE]
Definition at line 85 of file application.c.
update
char update[MAX_UPDATE_SIZE]
Definition at line 91 of file application.c.
update_response
char update_response[MAX_UPDATE_SIZE]
Definition at line 92 of file application.c.
wifible_attr
const osThreadAttr_t wifible_attr
Definition at line 77 of file application.c.
wifibleReceiver_attr
const osThreadAttr_t wifibleReceiver_attr
wifibleReceiverThreadId
osThreadId_t wifibleReceiverThreadId
wifibleThreadId
osThreadId_t wifibleThreadId
Definition at line 74 of file application.c.