Project DreamTeam: Core/Inc/wifi-ble.h File Reference
wifi-ble.h File Reference
#include "application.h"
#include "FreeRTOS.h"
#include "cmsis_os2.h"
#include "usart.h"
#include "ATcommands.h"
#include "stdbool.h"
#include "printf.h"
#include "string.h"
#include "helper.h"
Data Structures
struct wifible_module
A structure to provide flags for behaviour change of the module.
struct wifible_wifi_cfg
Structure to represent Wi-Fi configuration details.
struct wifible_bt_cfg
Structure to represent Bluetooth configuration details.
Macros
#define WIFIBLE_MODULE_STACK_SIZE 2048
#define WIFIBLE_MODULE_NAME "WIFIBLE"
#define WIFIBLE_MODULE_INIT_NAME "WifiBleInit"
#define WIFIBLE_RETVAL uint8_t
#define WIFIBLE_CMD_DELAY 100U
#define WIFIBLE_UART_BUFFER_SIZE 4096
#define WIFIBLE_POWER_ON 0xE1
#define WIFIBLE_POWER_OFF 0xE0
#define WIFIBLE_WIRELESS_MODE 0xCA
#define WIFIBLE_BLUETOOTH_MODE 0xCB
#define WIFIBLE_OK 0x00
#define WIFIBLE_FAILED_COPY 0x01
#define WIFIBLE_FAILED_SEMAPHORE 0x02
#define WIFIBLE_FAILED_FLAG 0x04
#define WIFIBLE_RESERVED 0x08
#define WIFIBLE_ALL_STATUS 0x0F
#define WIFIBLE_NOT_IMPLEMENTED 0xFA
#define WIFIBLE_MEM_ERROR 0xFB
#define WIFIBLE_POWER_ERROR 0xFC
#define WIFIBLE_RW_ERROR 0xFD
#define WIFIBLE_RESOURCE_ERROR 0xFE
#define WIFIBLE_INIT_ERROR 0xFF
Typedefs
typedef struct wifible_module wifible_module_t
A structure to provide flags for behaviour change of the module.
typedef struct wifible_wifi_cfg wifible_wifi_cfg_t
Structure to represent Wi-Fi configuration details.
typedef struct wifible_bt_cfg wifible_bt_cfg_t
Structure to represent Bluetooth configuration details.
Enumerations
enum wifi_mode { Station, SoftAP, Mixed }
Enum to represent Wi-Fi mode.
Functions
void StartWifiBleModule (void *argument)
An initialization task for this module.
void WifiReceiver (void *argument)
Task for handling Wi-Fi reception.
void BluetoothBeacon (void *argument)
Task for handling Bluetooth beacon.
wifible_wifi_cfg_t * wifible_wifi_default_cfg ()
Provides a default Wi-Fi configuration.
WIFIBLE_RETVAL wifible_wifi_clear_cfg (wifible_wifi_cfg_t *cfg)
Clears the provided Wi-Fi configuration.
WIFIBLE_RETVAL wifible_wifi_initialization (wifible_wifi_cfg_t *cfg)
Initializes the wifi module, using the provided configuration.
wifible_bt_cfg_t * wifible_bt_default_cfg ()
Provides a default Bluetooth configuration.
WIFIBLE_RETVAL wifible_bt_clear_cfg (wifible_bt_cfg_t *cfg)
Clears the provided Bluetooth configuration.
WIFIBLE_RETVAL wifible_bt_initialization (wifible_bt_cfg_t *cfg)
Initializes the bluetooth module, using the provided configuration.
WIFIBLE_RETVAL wifible_power_module (uint8_t power_state)
Powers the module on.
WIFIBLE_RETVAL wifible_handle_newData (size_t old_pos, size_t new_pos)
On IDLE_EVENT signal, checks uart1Buffer and decides copy-mechanism.
WIFIBLE_RETVAL wifible_enter_copy ()
enters the memory copy function and also clears previously allocated memory
WIFIBLE_RETVAL wifible_attempt_fullCopy (size_t start_pos, size_t length)
Copies data from uart1Buffer in 1 full step.
WIFIBLE_RETVAL wifible_attempt_partialCopy (size_t start_pos, size_t len1, size_t len2)
Copies data from uart1Buffer in 2 partial steps.
WIFIBLE_RETVAL wifible_handle_userInput ()
On USER_INPUT signal, forwards global 'input' variable to WIFIBLE over USART1.
WIFIBLE_RETVAL wifible_handle_newRequest ()
On NEW_REQUEST signal, responds to client via wifible_serve_webPage.
WIFIBLE_RETVAL wifible_serve_webPage (uint8_t link_id)
Serves a webpage or a JSON update to a client upon request over USART1.
void wifible_send_command (char *command, int length)
Sends the provided buffer to the WIFIBLE module.
WIFIBLE_RETVAL wifible_prep_peripherals ()
Prepares peripherals used in this module. Module fails to function without it.
bool wifible_failureHandler (WIFIBLE_RETVAL value)
Handles errors from wifible module functions. Serves as an error-handling wrapper for conditions.
Macro Definition Documentation
WIFIBLE_ALL_STATUS
#define WIFIBLE_ALL_STATUS 0x0F
Definition at line 46 of file wifi-ble.h.
WIFIBLE_BLUETOOTH_MODE
#define WIFIBLE_BLUETOOTH_MODE 0xCB
Definition at line 39 of file wifi-ble.h.
WIFIBLE_CMD_DELAY
#define WIFIBLE_CMD_DELAY 100U
Definition at line 32 of file wifi-ble.h.
WIFIBLE_FAILED_COPY
#define WIFIBLE_FAILED_COPY 0x01
Definition at line 42 of file wifi-ble.h.
WIFIBLE_FAILED_FLAG
#define WIFIBLE_FAILED_FLAG 0x04
Definition at line 44 of file wifi-ble.h.
WIFIBLE_FAILED_SEMAPHORE
#define WIFIBLE_FAILED_SEMAPHORE 0x02
Definition at line 43 of file wifi-ble.h.
WIFIBLE_INIT_ERROR
#define WIFIBLE_INIT_ERROR 0xFF
Definition at line 53 of file wifi-ble.h.
WIFIBLE_MEM_ERROR
#define WIFIBLE_MEM_ERROR 0xFB
Definition at line 49 of file wifi-ble.h.
WIFIBLE_MODULE_INIT_NAME
#define WIFIBLE_MODULE_INIT_NAME "WifiBleInit"
Definition at line 30 of file wifi-ble.h.
WIFIBLE_MODULE_NAME
#define WIFIBLE_MODULE_NAME "WIFIBLE"
Definition at line 29 of file wifi-ble.h.
WIFIBLE_MODULE_STACK_SIZE
#define WIFIBLE_MODULE_STACK_SIZE 2048
Definition at line 28 of file wifi-ble.h.
WIFIBLE_NOT_IMPLEMENTED
#define WIFIBLE_NOT_IMPLEMENTED 0xFA
Definition at line 48 of file wifi-ble.h.
WIFIBLE_OK
#define WIFIBLE_OK 0x00
Definition at line 41 of file wifi-ble.h.
WIFIBLE_POWER_ERROR
#define WIFIBLE_POWER_ERROR 0xFC
Definition at line 50 of file wifi-ble.h.
WIFIBLE_POWER_OFF
#define WIFIBLE_POWER_OFF 0xE0
Definition at line 36 of file wifi-ble.h.
WIFIBLE_POWER_ON
#define WIFIBLE_POWER_ON 0xE1
Definition at line 35 of file wifi-ble.h.
WIFIBLE_RESERVED
#define WIFIBLE_RESERVED 0x08
Definition at line 45 of file wifi-ble.h.
WIFIBLE_RESOURCE_ERROR
#define WIFIBLE_RESOURCE_ERROR 0xFE
Definition at line 52 of file wifi-ble.h.
WIFIBLE_RETVAL
#define WIFIBLE_RETVAL uint8_t
Definition at line 31 of file wifi-ble.h.
WIFIBLE_RW_ERROR
#define WIFIBLE_RW_ERROR 0xFD
Definition at line 51 of file wifi-ble.h.
WIFIBLE_UART_BUFFER_SIZE
#define WIFIBLE_UART_BUFFER_SIZE 4096
Definition at line 33 of file wifi-ble.h.
WIFIBLE_WIRELESS_MODE
#define WIFIBLE_WIRELESS_MODE 0xCA
Definition at line 38 of file wifi-ble.h.
Typedef Documentation
wifible_bt_cfg_t
typedef struct wifible_bt_cfg wifible_bt_cfg_t
Structure to represent Bluetooth configuration details.
wifible_module_t
typedef struct wifible_module wifible_module_t
A structure to provide flags for behaviour change of the module.
Note
Initializes module either as WIFI or BLUETOOTh. Currently only WIFI is implemented.
wifible_wifi_cfg_t
typedef struct wifible_wifi_cfg wifible_wifi_cfg_t
Structure to represent Wi-Fi configuration details.
Enumeration Type Documentation
wifi_mode
enum wifi_mode
Enum to represent Wi-Fi mode.
Note
Not to be confused with module mode, which is either BLUETOOTH or WIFI
Enumerator
Station
SoftAP
Mixed
Definition at line 61 of file wifi-ble.h.
Function Documentation
BluetoothBeacon()
void BluetoothBeacon (void * argument)
Task for handling Bluetooth beacon.
Parameters
argument ... ignored / not used
Definition at line 162 of file wifi-ble.c.
References Error_Handler().
StartWifiBleModule()
void StartWifiBleModule (void * argument)
An initialization task for this module.
Parameters
argument ... provide wifible_module_t for module behaviour change
Definition at line 79 of file wifi-ble.c.
References BluetoothBeacon(), wifible_module::mode, wifible_attr, WIFIBLE_BLUETOOTH_MODE, wifible_bt_default_cfg(), wifible_bt_initialization(), wifible_prep_peripherals(), wifible_wifi_default_cfg(), wifible_wifi_initialization(), WIFIBLE_WIRELESS_MODE, wifibleThreadId, and WifiReceiver().
wifible_attempt_fullCopy()
WIFIBLE_RETVAL wifible_attempt_fullCopy (size_t start_pos, size_t length)
Copies data from uart1Buffer in 1 full step.
Parameters
start_pos ... the start position of the data to copy
length ... the length from start_pos to end of data
Returns
either error or status macros, WIFIBLE_OK on success
Definition at line 373 of file wifi-ble.c.
References flagErrorHandler(), MSG_EVENT, msgSem, newMsg, parserThreadId, release_semaphore(), uart1Buffer, wifible_enter_copy(), WIFIBLE_FAILED_FLAG, WIFIBLE_MEM_ERROR, WIFIBLE_OK, and WIFIBLE_RETVAL.
wifible_attempt_partialCopy()
WIFIBLE_RETVAL wifible_attempt_partialCopy (size_t start_pos, size_t len1, size_t len2)
Copies data from uart1Buffer in 2 partial steps.
Note
1st partial: start_pos to end of buffer using len1, 2nd partial: start of buffer to len2
Parameters
start_pos ... the start position of the data to copy
len1 ... the length from start to end of buffer
len2 ... the length from start of buffer to end of data
Returns
either error or status macros, WIFIBLE_OK on success
Definition at line 400 of file wifi-ble.c.
References flagErrorHandler(), MSG_EVENT, msgSem, newMsg, parserThreadId, release_semaphore(), uart1Buffer, wifible_enter_copy(), WIFIBLE_FAILED_FLAG, WIFIBLE_MEM_ERROR, WIFIBLE_OK, and WIFIBLE_RETVAL.
wifible_bt_clear_cfg()
WIFIBLE_RETVAL wifible_bt_clear_cfg (wifible_bt_cfg_t * cfg)
Clears the provided Bluetooth configuration.
Parameters
cfg ... pointer to a wifible_bt_cfg_t to be free'd from memory
Returns
either error or status macros, WIFIBLE_OK on success
Definition at line 291 of file wifi-ble.c.
References WIFIBLE_NOT_IMPLEMENTED.
wifible_bt_default_cfg()
wifible_bt_cfg_t* wifible_bt_default_cfg ()
Provides a default Bluetooth configuration.
Returns
a pointer to an allocated wifible_bt_cfg_t structure, which will be filled with default settings
Definition at line 287 of file wifi-ble.c.
wifible_bt_initialization()
WIFIBLE_RETVAL wifible_bt_initialization (wifible_bt_cfg_t * cfg)
Initializes the bluetooth module, using the provided configuration.
Parameters
cfg ... pointer to a wifible_bt_cfg_t to be used for configuration
Returns
either error or status macros, WIFIBLE_OK on success
Definition at line 295 of file wifi-ble.c.
References WIFIBLE_NOT_IMPLEMENTED.
wifible_enter_copy()
WIFIBLE_RETVAL wifible_enter_copy ()
enters the memory copy function and also clears previously allocated memory
Returns
either error or status macros, WIFIBLE_OK on success
Definition at line 363 of file wifi-ble.c.
References acquire_semaphore(), MODULE_SEM_TIMEOUT, msgSem, newMsg, WIFIBLE_FAILED_COPY, and WIFIBLE_OK.
wifible_failureHandler()
bool wifible_failureHandler (WIFIBLE_RETVAL value)
Handles errors from wifible module functions. Serves as an error-handling wrapper for conditions.
Parameters
value ... return value of any WIFIBLE module function
Returns
true on failure values, false on successful values
Definition at line 551 of file wifi-ble.c.
References newLine, printf_(), WIFIBLE_FAILED_COPY, WIFIBLE_FAILED_FLAG, WIFIBLE_FAILED_SEMAPHORE, WIFIBLE_INIT_ERROR, WIFIBLE_MEM_ERROR, WIFIBLE_OK, WIFIBLE_POWER_ERROR, WIFIBLE_RESOURCE_ERROR, and WIFIBLE_RW_ERROR.
wifible_handle_newData()
WIFIBLE_RETVAL wifible_handle_newData (size_t old_pos, size_t new_pos)
On IDLE_EVENT signal, checks uart1Buffer and decides copy-mechanism.
Returns
either error or status macros, WIFIBLE_OK on success
Definition at line 304 of file wifi-ble.c.
References halStatusHandler(), huart2, printf_(), translate_UART_Error(), uart1Buffer, wifible_attempt_fullCopy(), wifible_attempt_partialCopy(), and WIFIBLE_UART_BUFFER_SIZE.
wifible_handle_newRequest()
WIFIBLE_RETVAL wifible_handle_newRequest ()
On NEW_REQUEST signal, responds to client via wifible_serve_webPage.
Returns
either error or status macros, WIFIBLE_OK on success
Definition at line 446 of file wifi-ble.c.
References responseLink, WIFIBLE_RETVAL, and wifible_serve_webPage().
wifible_handle_userInput()
WIFIBLE_RETVAL wifible_handle_userInput ()
On USER_INPUT signal, forwards global 'input' variable to WIFIBLE over USART1.
Returns
either error or status macros, WIFIBLE_OK on success
Definition at line 429 of file wifi-ble.c.
References acquire_semaphore(), AT_CMD_BUFFER_SIZE, at_execute_command(), input, inputSem, MODULE_SEM_TIMEOUT, release_semaphore(), WIFIBLE_OK, WIFIBLE_RETVAL, and wifible_send_command().
wifible_power_module()
WIFIBLE_RETVAL wifible_power_module (uint8_t power_state)
Powers the module on.
Note
Currently not implemented
Returns
either error or status macros, WIFIBLE_OK on success
Definition at line 299 of file wifi-ble.c.
References WIFIBLE_NOT_IMPLEMENTED.
wifible_prep_peripherals()
WIFIBLE_RETVAL wifible_prep_peripherals ()
Prepares peripherals used in this module. Module fails to function without it.
Returns
either error or status macros, WIFIBLE_OK on success
Definition at line 532 of file wifi-ble.c.
References halStatusHandler(), huart1, printf_(), translate_UART_Error(), uart1Buffer, WIFIBLE_OK, WIFIBLE_RESOURCE_ERROR, WIFIBLE_UART_BUFFER_SIZE, and wifible_uart_receive_callback().
wifible_send_command()
void wifible_send_command (char * command, int length)
Sends the provided buffer to the WIFIBLE module.
Note
This is a suitable callback function for the wrappers in ATcommands.c
Parameters
command ... buffer to be sent over USART1
length ... length of buffer
Returns
either error or status macros, WIFIBLE_OK on success
Definition at line 510 of file wifi-ble.c.
References halStatusHandler(), huart1, newLine, printf_(), and translate_UART_Error().
wifible_serve_webPage()
WIFIBLE_RETVAL wifible_serve_webPage (uint8_t link_id)
Serves a webpage or a JSON update to a client upon request over USART1.
Note
ALL connections will be dropped in this function, because programming is hard
Parameters
link_id ... connection link id of client
Returns
either error or status macros, WIFIBLE_OK on success
Definition at line 464 of file wifi-ble.c.
References AT_CMD_BUFFER_SIZE, AT_IP_CloseConnection, AT_IP_Send, at_set_command(), halStatusHandler(), heartrate_ram, HTTP_CONTENT_LENGTH_TEMPLATE, HTTP_CONTENT_TYPE_JSON, HTTP_HEADER, huart1, JSON_REQUEST, newLine, page_response, page_response_length, printf_(), requestType, sprintf_(), translate_UART_Error(), update, update_response, WIFIBLE_CMD_DELAY, WIFIBLE_OK, WIFIBLE_RW_ERROR, and wifible_send_command().
wifible_wifi_clear_cfg()
WIFIBLE_RETVAL wifible_wifi_clear_cfg (wifible_wifi_cfg_t * cfg)
Clears the provided Wi-Fi configuration.
Parameters
cfg ... pointer to a wifible_wifi_cfg_t to be free'd from memory
Returns
either error or status macros, WIFIBLE_OK on success
Definition at line 212 of file wifi-ble.c.
References wifible_wifi_cfg::domain, wifible_wifi_cfg::hostname, wifible_wifi_cfg::local_gw, wifible_wifi_cfg::local_ip, wifible_wifi_cfg::local_netmask, wifible_wifi_cfg::pwd, wifible_wifi_cfg::ssid, and WIFIBLE_OK.
wifible_wifi_default_cfg()
wifible_wifi_cfg_t* wifible_wifi_default_cfg ()
Provides a default Wi-Fi configuration.
Returns
a pointer to an allocated wifible_wifi_cfg_t structure, which will be filled with default settings
Definition at line 168 of file wifi-ble.c.
References wifible_wifi_cfg::domain, wifible_wifi_cfg::hostname, HTML_TEMPLATE, HTTP_CONTENT_LENGTH_TEMPLATE, HTTP_CONTENT_TYPE_HTML, HTTP_HEADER, wifible_wifi_cfg::local_gw, wifible_wifi_cfg::local_ip, wifible_wifi_cfg::local_netmask, wifible_wifi_cfg::mode, page, page_response, page_response_length, wifible_wifi_cfg::pwd, SoftAP, sprintf_(), and wifible_wifi_cfg::ssid.
wifible_wifi_initialization()
WIFIBLE_RETVAL wifible_wifi_initialization (wifible_wifi_cfg_t * cfg)
Initializes the wifi module, using the provided configuration.
Parameters
cfg ... pointer to a wifible_wifi_cfg_t to be used for configuration
Returns
either error or status macros, WIFIBLE_OK on success
Definition at line 224 of file wifi-ble.c.
References AT_CMD_BUFFER_SIZE, AT_Disable, AT_Enable, at_execute_command(), AT_IP_ConnectionMode_Multiple, AT_IP_Server, AT_IP_Server_Create, AT_IP_Set_MultiConnectionMode, AT_IP_Set_SoftAP_IP, AT_IP_Set_SoftAP_MAC, at_query_command(), at_set_command(), AT_Startup, AT_Version, AT_WIFI_Enable_DHCP, AT_WIFI_Encryption_OPEN, AT_WIFI_MDNS, AT_WIFI_Set_DHCP_Range, AT_WIFI_Set_Hostname, AT_WIFI_Set_Mode, AT_WIFI_Set_SoftAP_Config, AT_WIFI_SoftAP_Mode, wifible_wifi_cfg::hostname, wifible_wifi_cfg::local_gw, wifible_wifi_cfg::local_ip, wifible_wifi_cfg::local_netmask, newLine, printf_(), wifible_wifi_cfg::pwd, wifible_wifi_cfg::ssid, WIFIBLE_CMD_DELAY, WIFIBLE_OK, and wifible_send_command().
WifiReceiver()
void WifiReceiver (void * argument)
Task for handling Wi-Fi reception.
Parameters
argument ... ignored / not used
Definition at line 106 of file wifi-ble.c.
References COPY_REATTEMPT, flagErrorHandler(), huart1, IDLE_EVENT, NEW_RESPONSE, newLine, parserThreadId, printf_(), USER_INPUT, WIFIBLE_FAILED_COPY, wifible_failureHandler(), wifible_handle_newData(), wifible_handle_newRequest(), wifible_handle_userInput(), WIFIBLE_RETVAL, and WIFIBLE_UART_BUFFER_SIZE.