Project DreamTeam: Core/Inc/max30101.h File Reference
max30101.h File Reference
#include <stdbool.h>
#include "stm32l4xx_hal.h"
#include "cmsis_os2.h"
Data Structures
struct MAX30101
struct MAX30101_SAMPLE
Macros
#define DATA_MODE 0
#define MAX_READ_SIZE 64
#define MAX_SAMPLES 16
#define CHANNEL_SIZE 3
#define SAMPLE_SIZE 3
#define ACTIVE_LED_CHANNELS 1
#define LED_CURRENT 31
#define MAX_RETRY 20
#define HR_SAMPLE_SIZE 300
#define DELTA_SAMPLE 8
#define DELTA_NEG_THRES -25
#define INTERR_NON 0x00
#define INTERR_FLAG 0x01
#define HR_THRESHOLD 100000
#define SLAVE_ID 0x57
#define MAX30101_I2C_WRITE 0xAE
#define MAX30101_I2C_READ 0xAF
#define SETUP_DELAY 20
#define I2C_TIMEOUT 100
#define UART_TIMEOUT 30
#define WRITE 0x00
#define READ 0x01
#define INTERRUPT_STATUS01 0x00
#define INTERRUPT_STATUS02 0x01
#define INTERRUPT_ENABLE01 0x02
#define INTERRUPT_ENABLE02 0x03
#define FIFO_WR_PTR 0x04
#define FIFO_OVF_COUNTER 0x05
#define FIFO_RD_PTR 0x06
#define FIFO_DATA 0x07
#define FIFO_CONFIG 0x08
#define FIFO_SMP_AVE_DIS 0x00
#define FIFO_SMP_AVE_2 0x20
#define FIFO_SMP_AVE_4 0x40
#define FIFO_SMP_AVE_8 0x60
#define FIFO_SMP_AVE_16 0x80
#define FIFO_SMP_AVE_32 0xA0
#define FIFO_ROLLOVER_EN 0x10
#define FIFO_ROLLOVER_DIS 0x00
#define FIFO_A_FULL_0 0x00
#define FIFO_A_FULL_8 0x08
#define FIFO_A_FULL_16 0x0F
#define FIFO_A_FULL_14 0x0E
#define FIFO_A_FULL_24 0x08
#define MODE_CONFIG 0x09
#define MODE_SHDN 0x80
#define MODE_RESET 0x40
#define MODE_HR 0x02
#define MODE_SPO2 0x03
#define MODE_MULTI_LED 0x07
#define SPO2_CONFIG 0x0A
#define SPO2_ADC_RGE_00 0x00
#define SPO2_ADC_RGE_01 0x10
#define SPO2_ADC_RGE_02 0x20
#define SPO2_ADC_RGE_03 0x30
#define SPO2_SR_50 0x00
#define SPO2_SR_100 0x04
#define SPO2_SR_200 0x08
#define SPO2_SR_400 0x0C
#define SPO2_SR_800 0x10
#define SPO2_SR_1000 0x11
#define SPO2_SR_1600 0x18
#define SPO2_SR_3200 0x1C
#define SPO2_LED_PW69 0x00
#define SPO2_LED_PW118 0x01
#define SPO2_LED_PW215 0x02
#define SPO2_LED_PW411 0x03
#define LED_PulseAmp_LED1_PA 0x0C
#define LED_PulseAmp_LED2_PA 0x0D
#define LED_PulseAmp_LED3_PA 0x0E
#define LED_PulseAmp_LED4_PA 0x0F
#define MULTI_LED_SLOT01_AND_02 0x11
#define MULTI_LED_SLOT03_AND_04 0x12
#define MULTI_LED_SLOT01_NONE 0x00
#define MULTI_LED_SLOT01_LED1_RED 0x01
#define MULTI_LED_SLOT01_LED2_IR 0x02
#define MULTI_LED_SLOT01_LED3_GREEN 0x03
#define MULTI_LED_SLOT01_LED4_GREEN 0x03
#define MULTI_LED_SLOT02_NONE 0x00
#define MULTI_LED_SLOT02_LED1_RED 0x10
#define MULTI_LED_SLOT02_LED2_IR 0x20
#define MULTI_LED_SLOT02_LED3_GREEN 0x30
#define MULTI_LED_SLOT02_LED4_GREEN 0x30
#define MULTI_LED_SLOT03_NONE 0x00
#define MULTI_LED_SLOT03_LED1_RED 0x01
#define MULTI_LED_SLOT03_LED2_IR 0x02
#define MULTI_LED_SLOT03_LED3_GREEN 0x03
#define MULTI_LED_SLOT03_LED4_GREEN 0x03
#define MULTI_LED_SLOT04_NONE 0x00
#define MULTI_LED_SLOT04_LED1_RED 0x10
#define MULTI_LED_SLOT04_LED2_IR 0x20
#define MULTI_LED_SLOT04_LED3_GREEN 0x30
#define MULTI_LED_SLOT04_LED4_GREEN 0x30
#define TEMP_INTEGER 0x1F
#define TEMP_FRACTION 0x20
#define DIE_TEMP_CONFIG 0x21
#define TEMP_EN 0x01
#define IE01 0x02
#define IE01_A_FULL_EN 0x80
#define FIFO_FULL 0x80
#define IE01_PPG_RDY_EN 0x40
#define PPG_RDY 0x40
#define IE01_ALC_OVF_EN 0x20
#define ALC_OVF 0x20
#define PWR_RDY 0x00
#define IE02 0x03
#define IE02_DIE_TEMP_RDY_EN 0x03
#define DIE_TEMP_RDY 0x02
Typedefs
typedef struct MAX30101 MAX30101
typedef struct MAX30101_SAMPLE MAX30101_SAMPLE
Enumerations
enum INIT_STATUS {
INIT_OK = 0x00, REVISION_FAILED, REVISION_FALSE, RESET_FAILED,
CONFIG_FAILED, SPO2_CONFIG_FAILED, INITIAL_TEMP_FAILED, LED_CONFIG_FAILED,
RES_SEN_FAILED, RES_SEN_SUCCESS = 0x0B, GET_REG_FAILED, GET_REG_SUCCESS,
SET_REG_FAILED, SET_REG_SUCCESS, FLAG_SET, FLAG_NOT_SET,
FIFO_READ_SUCCESS, FIFO_READ_FAILURE, READ_SAMPLE_SET_SUCCESS, READ_SAMPLE_SET_FAILURE,
CALIBRATION_SUCCESS, CALIBRATION_FAILURE
}
Functions
INIT_STATUS MAX30101_initialize (MAX30101 *sensor)
void translate_I2C_Error (I2C_HandleTypeDef *hi2c)
INIT_STATUS MAX30101_read_sample (MAX30101 *sensor, MAX30101_SAMPLE *sample)
INIT_STATUS MAX30101_reset (MAX30101 *sensor)
INIT_STATUS MAX30101_clear_FIFO (MAX30101 *sensor)
INIT_STATUS MAX30101_get_interrupt_enabled01 (MAX30101 *sensor, uint8_t *reg_value)
INIT_STATUS MAX30101_set_interrupt_enabled01 (MAX30101 *sensor, uint8_t *reg_value)
INIT_STATUS MAX30101_get_interrupt_status01 (MAX30101 *sensor, uint8_t *reg_value)
INIT_STATUS MAX30101_set_interrupt_status01 (MAX30101 *sensor, uint8_t *reg_value)
bool MAX30101_get_interr_PPG_RDY (MAX30101 *sensor)
bool MAX30101_get_interr_A_FULL (MAX30101 *sensor)
INIT_STATUS MAX30101_get_interrupt_enabled02 (MAX30101 *sensor, uint8_t *reg_value)
INIT_STATUS MAX30101_set_interrupt_enabled02 (MAX30101 *sensor, uint8_t *reg_value)
INIT_STATUS MAX30101_get_interrupt_status02 (MAX30101 *sensor, uint8_t *reg_value)
INIT_STATUS MAX30101_set_interrupt_status02 (MAX30101 *sensor, uint8_t *reg_value)
INIT_STATUS MAX30101_get_FIFO_config (MAX30101 *sensor, uint8_t *reg_value)
INIT_STATUS MAX30101_set_FIFO_config (MAX30101 *sensor, uint8_t *reg_value)
INIT_STATUS MAX30101_get_MODE_config (MAX30101 *sensor, uint8_t *reg_value)
INIT_STATUS MAX30101_set_MODE_config (MAX30101 *sensor, uint8_t *reg_value)
INIT_STATUS MAX30101_get_SPO2_config (MAX30101 *sensor, uint8_t *reg_value)
INIT_STATUS MAX30101_set_SPO2_config (MAX30101 *sensor, uint8_t *reg_value)
INIT_STATUS MAX30101_set_LED1_PA_config (MAX30101 *sensor, uint8_t *reg_value)
INIT_STATUS MAX30101_get_LED1_PA_config (MAX30101 *sensor, uint8_t *reg_value)
INIT_STATUS MAX30101_set_LED2_PA_config (MAX30101 *sensor, uint8_t *reg_value)
INIT_STATUS MAX30101_get_LED2_PA_config (MAX30101 *sensor, uint8_t *reg_value)
INIT_STATUS MAX30101_set_LED3_PA_config (MAX30101 *sensor, uint8_t *reg_value)
INIT_STATUS MAX30101_get_LED3_PA_config (MAX30101 *sensor, uint8_t *reg_value)
INIT_STATUS MAX30101_set_LED4_PA_config (MAX30101 *sensor, uint8_t *reg_value)
INIT_STATUS MAX30101_get_LED4_PA_config (MAX30101 *sensor, uint8_t *reg_value)
INIT_STATUS MAX30101_get_mulit_led_slot_0102_PA_config (MAX30101 *sensor, uint8_t *reg)
INIT_STATUS MAX30101_set_mulit_led_slot_0102_PA_config (MAX30101 *sensor, uint8_t *reg)
INIT_STATUS MAX30101_get_mulit_led_slot_0304_PA_config (MAX30101 *sensor, uint8_t *reg_value)
INIT_STATUS MAX30101_set_mulit_led_slot_0304_PA_config (MAX30101 *sensor, uint8_t *reg_value)
INIT_STATUS MAX30101_get_temp_int (MAX30101 *sensor, uint8_t *reg_value)
INIT_STATUS MAX30101_get_temp_frac_int (MAX30101 *sensor, uint8_t *reg_value)
INIT_STATUS MAX30101_set_temp_en_int (MAX30101 *sensor, uint8_t *reg_value)
HAL_StatusTypeDef MAX30101_read_register (MAX30101 *sensor, uint8_t reg, uint8_t *data)
HAL_StatusTypeDef MAX30101_read_registers (MAX30101 *sensor, uint8_t reg, uint8_t *data, uint8_t size)
HAL_StatusTypeDef MAX30101_write_register (MAX30101 *sensor, uint8_t reg, uint8_t *data)
Variables
UART_HandleTypeDef huart2
Macro Definition Documentation
ACTIVE_LED_CHANNELS
#define ACTIVE_LED_CHANNELS 1
Definition at line 18 of file max30101.h.
ALC_OVF
#define ALC_OVF 0x20
Definition at line 244 of file max30101.h.
CHANNEL_SIZE
#define CHANNEL_SIZE 3
Definition at line 16 of file max30101.h.
DATA_MODE
#define DATA_MODE 0
Definition at line 13 of file max30101.h.
DELTA_NEG_THRES
#define DELTA_NEG_THRES -25
Definition at line 23 of file max30101.h.
DELTA_SAMPLE
#define DELTA_SAMPLE 8
Definition at line 22 of file max30101.h.
DIE_TEMP_CONFIG
#define DIE_TEMP_CONFIG 0x21
Definition at line 206 of file max30101.h.
DIE_TEMP_RDY
#define DIE_TEMP_RDY 0x02
Definition at line 264 of file max30101.h.
FIFO_A_FULL_0
#define FIFO_A_FULL_0 0x00
Definition at line 68 of file max30101.h.
FIFO_A_FULL_14
#define FIFO_A_FULL_14 0x0E
Definition at line 71 of file max30101.h.
FIFO_A_FULL_16
#define FIFO_A_FULL_16 0x0F
Definition at line 70 of file max30101.h.
FIFO_A_FULL_24
#define FIFO_A_FULL_24 0x08
Definition at line 72 of file max30101.h.
FIFO_A_FULL_8
#define FIFO_A_FULL_8 0x08
Definition at line 69 of file max30101.h.
FIFO_CONFIG
#define FIFO_CONFIG 0x08
Definition at line 52 of file max30101.h.
FIFO_DATA
#define FIFO_DATA 0x07
Definition at line 50 of file max30101.h.
FIFO_FULL
#define FIFO_FULL 0x80
Definition at line 228 of file max30101.h.
FIFO_OVF_COUNTER
#define FIFO_OVF_COUNTER 0x05
Definition at line 48 of file max30101.h.
FIFO_RD_PTR
#define FIFO_RD_PTR 0x06
Definition at line 49 of file max30101.h.
FIFO_ROLLOVER_DIS
#define FIFO_ROLLOVER_DIS 0x00
Definition at line 61 of file max30101.h.
FIFO_ROLLOVER_EN
#define FIFO_ROLLOVER_EN 0x10
Definition at line 60 of file max30101.h.
FIFO_SMP_AVE_16
#define FIFO_SMP_AVE_16 0x80
Definition at line 57 of file max30101.h.
FIFO_SMP_AVE_2
#define FIFO_SMP_AVE_2 0x20
Definition at line 54 of file max30101.h.
FIFO_SMP_AVE_32
#define FIFO_SMP_AVE_32 0xA0
Definition at line 58 of file max30101.h.
FIFO_SMP_AVE_4
#define FIFO_SMP_AVE_4 0x40
Definition at line 55 of file max30101.h.
FIFO_SMP_AVE_8
#define FIFO_SMP_AVE_8 0x60
Definition at line 56 of file max30101.h.
FIFO_SMP_AVE_DIS
#define FIFO_SMP_AVE_DIS 0x00
Definition at line 53 of file max30101.h.
FIFO_WR_PTR
#define FIFO_WR_PTR 0x04
Definition at line 47 of file max30101.h.
HR_SAMPLE_SIZE
#define HR_SAMPLE_SIZE 300
Definition at line 21 of file max30101.h.
HR_THRESHOLD
#define HR_THRESHOLD 100000
Definition at line 28 of file max30101.h.
I2C_TIMEOUT
#define I2C_TIMEOUT 100
Definition at line 35 of file max30101.h.
IE01
#define IE01 0x02
Definition at line 226 of file max30101.h.
IE01_A_FULL_EN
#define IE01_A_FULL_EN 0x80
Definition at line 227 of file max30101.h.
IE01_ALC_OVF_EN
#define IE01_ALC_OVF_EN 0x20
Definition at line 243 of file max30101.h.
IE01_PPG_RDY_EN
#define IE01_PPG_RDY_EN 0x40
Definition at line 235 of file max30101.h.
IE02
#define IE02 0x03
Definition at line 261 of file max30101.h.
IE02_DIE_TEMP_RDY_EN
#define IE02_DIE_TEMP_RDY_EN 0x03
Definition at line 262 of file max30101.h.
INTERR_FLAG
#define INTERR_FLAG 0x01
Definition at line 26 of file max30101.h.
INTERR_NON
#define INTERR_NON 0x00
Definition at line 25 of file max30101.h.
INTERRUPT_ENABLE01
#define INTERRUPT_ENABLE01 0x02
Definition at line 44 of file max30101.h.
INTERRUPT_ENABLE02
#define INTERRUPT_ENABLE02 0x03
Definition at line 45 of file max30101.h.
INTERRUPT_STATUS01
#define INTERRUPT_STATUS01 0x00
Definition at line 42 of file max30101.h.
INTERRUPT_STATUS02
#define INTERRUPT_STATUS02 0x01
Definition at line 43 of file max30101.h.
LED_CURRENT
#define LED_CURRENT 31
Definition at line 19 of file max30101.h.
LED_PulseAmp_LED1_PA
#define LED_PulseAmp_LED1_PA 0x0C
Definition at line 141 of file max30101.h.
LED_PulseAmp_LED2_PA
#define LED_PulseAmp_LED2_PA 0x0D
Definition at line 142 of file max30101.h.
LED_PulseAmp_LED3_PA
#define LED_PulseAmp_LED3_PA 0x0E
Definition at line 143 of file max30101.h.
LED_PulseAmp_LED4_PA
#define LED_PulseAmp_LED4_PA 0x0F
Definition at line 144 of file max30101.h.
MAX30101_I2C_READ
#define MAX30101_I2C_READ 0xAF
Definition at line 33 of file max30101.h.
MAX30101_I2C_WRITE
#define MAX30101_I2C_WRITE 0xAE
Definition at line 32 of file max30101.h.
MAX_READ_SIZE
#define MAX_READ_SIZE 64
Definition at line 14 of file max30101.h.
MAX_RETRY
#define MAX_RETRY 20
Definition at line 20 of file max30101.h.
MAX_SAMPLES
#define MAX_SAMPLES 16
Definition at line 15 of file max30101.h.
MODE_CONFIG
#define MODE_CONFIG 0x09
Definition at line 81 of file max30101.h.
MODE_HR
#define MODE_HR 0x02
Definition at line 97 of file max30101.h.
MODE_MULTI_LED
#define MODE_MULTI_LED 0x07
Definition at line 99 of file max30101.h.
MODE_RESET
#define MODE_RESET 0x40
Definition at line 89 of file max30101.h.
MODE_SHDN
#define MODE_SHDN 0x80
Definition at line 82 of file max30101.h.
MODE_SPO2
#define MODE_SPO2 0x03
Definition at line 98 of file max30101.h.
MULTI_LED_SLOT01_AND_02
#define MULTI_LED_SLOT01_AND_02 0x11
Definition at line 147 of file max30101.h.
MULTI_LED_SLOT01_LED1_RED
#define MULTI_LED_SLOT01_LED1_RED 0x01
Definition at line 159 of file max30101.h.
MULTI_LED_SLOT01_LED2_IR
#define MULTI_LED_SLOT01_LED2_IR 0x02
Definition at line 160 of file max30101.h.
MULTI_LED_SLOT01_LED3_GREEN
#define MULTI_LED_SLOT01_LED3_GREEN 0x03
Definition at line 161 of file max30101.h.
MULTI_LED_SLOT01_LED4_GREEN
#define MULTI_LED_SLOT01_LED4_GREEN 0x03
Definition at line 162 of file max30101.h.
MULTI_LED_SLOT01_NONE
#define MULTI_LED_SLOT01_NONE 0x00
Definition at line 158 of file max30101.h.
MULTI_LED_SLOT02_LED1_RED
#define MULTI_LED_SLOT02_LED1_RED 0x10
Definition at line 165 of file max30101.h.
MULTI_LED_SLOT02_LED2_IR
#define MULTI_LED_SLOT02_LED2_IR 0x20
Definition at line 166 of file max30101.h.
MULTI_LED_SLOT02_LED3_GREEN
#define MULTI_LED_SLOT02_LED3_GREEN 0x30
Definition at line 167 of file max30101.h.
MULTI_LED_SLOT02_LED4_GREEN
#define MULTI_LED_SLOT02_LED4_GREEN 0x30
Definition at line 168 of file max30101.h.
MULTI_LED_SLOT02_NONE
#define MULTI_LED_SLOT02_NONE 0x00
Definition at line 164 of file max30101.h.
MULTI_LED_SLOT03_AND_04
#define MULTI_LED_SLOT03_AND_04 0x12
Definition at line 148 of file max30101.h.
MULTI_LED_SLOT03_LED1_RED
#define MULTI_LED_SLOT03_LED1_RED 0x01
Definition at line 171 of file max30101.h.
MULTI_LED_SLOT03_LED2_IR
#define MULTI_LED_SLOT03_LED2_IR 0x02
Definition at line 172 of file max30101.h.
MULTI_LED_SLOT03_LED3_GREEN
#define MULTI_LED_SLOT03_LED3_GREEN 0x03
Definition at line 173 of file max30101.h.
MULTI_LED_SLOT03_LED4_GREEN
#define MULTI_LED_SLOT03_LED4_GREEN 0x03
Definition at line 174 of file max30101.h.
MULTI_LED_SLOT03_NONE
#define MULTI_LED_SLOT03_NONE 0x00
Definition at line 170 of file max30101.h.
MULTI_LED_SLOT04_LED1_RED
#define MULTI_LED_SLOT04_LED1_RED 0x10
Definition at line 177 of file max30101.h.
MULTI_LED_SLOT04_LED2_IR
#define MULTI_LED_SLOT04_LED2_IR 0x20
Definition at line 178 of file max30101.h.
MULTI_LED_SLOT04_LED3_GREEN
#define MULTI_LED_SLOT04_LED3_GREEN 0x30
Definition at line 179 of file max30101.h.
MULTI_LED_SLOT04_LED4_GREEN
#define MULTI_LED_SLOT04_LED4_GREEN 0x30
Definition at line 180 of file max30101.h.
MULTI_LED_SLOT04_NONE
#define MULTI_LED_SLOT04_NONE 0x00
Definition at line 176 of file max30101.h.
PPG_RDY
#define PPG_RDY 0x40
Definition at line 236 of file max30101.h.
PWR_RDY
#define PWR_RDY 0x00
Definition at line 252 of file max30101.h.
READ
#define READ 0x01
Definition at line 38 of file max30101.h.
SAMPLE_SIZE
#define SAMPLE_SIZE 3
Definition at line 17 of file max30101.h.
SETUP_DELAY
#define SETUP_DELAY 20
Definition at line 34 of file max30101.h.
SLAVE_ID
#define SLAVE_ID 0x57
Definition at line 31 of file max30101.h.
SPO2_ADC_RGE_00
#define SPO2_ADC_RGE_00 0x00
Definition at line 106 of file max30101.h.
SPO2_ADC_RGE_01
#define SPO2_ADC_RGE_01 0x10
Definition at line 107 of file max30101.h.
SPO2_ADC_RGE_02
#define SPO2_ADC_RGE_02 0x20
Definition at line 108 of file max30101.h.
SPO2_ADC_RGE_03
#define SPO2_ADC_RGE_03 0x30
Definition at line 109 of file max30101.h.
SPO2_CONFIG
#define SPO2_CONFIG 0x0A
Definition at line 102 of file max30101.h.
SPO2_LED_PW118
#define SPO2_LED_PW118 0x01
Definition at line 136 of file max30101.h.
SPO2_LED_PW215
#define SPO2_LED_PW215 0x02
Definition at line 137 of file max30101.h.
SPO2_LED_PW411
#define SPO2_LED_PW411 0x03
Definition at line 138 of file max30101.h.
SPO2_LED_PW69
#define SPO2_LED_PW69 0x00
Definition at line 135 of file max30101.h.
SPO2_SR_100
#define SPO2_SR_100 0x04
Definition at line 120 of file max30101.h.
SPO2_SR_1000
#define SPO2_SR_1000 0x11
Definition at line 124 of file max30101.h.
SPO2_SR_1600
#define SPO2_SR_1600 0x18
Definition at line 125 of file max30101.h.
SPO2_SR_200
#define SPO2_SR_200 0x08
Definition at line 121 of file max30101.h.
SPO2_SR_3200
#define SPO2_SR_3200 0x1C
Definition at line 126 of file max30101.h.
SPO2_SR_400
#define SPO2_SR_400 0x0C
Definition at line 122 of file max30101.h.
SPO2_SR_50
#define SPO2_SR_50 0x00
Definition at line 119 of file max30101.h.
SPO2_SR_800
#define SPO2_SR_800 0x10
Definition at line 123 of file max30101.h.
TEMP_EN
#define TEMP_EN 0x01
Definition at line 207 of file max30101.h.
TEMP_FRACTION
#define TEMP_FRACTION 0x20
Definition at line 198 of file max30101.h.
TEMP_INTEGER
#define TEMP_INTEGER 0x1F
Definition at line 182 of file max30101.h.
UART_TIMEOUT
#define UART_TIMEOUT 30
Definition at line 36 of file max30101.h.
WRITE
#define WRITE 0x00
Definition at line 37 of file max30101.h.
Typedef Documentation
MAX30101
typedef struct MAX30101 MAX30101
MAX30101_SAMPLE
typedef struct MAX30101_SAMPLE MAX30101_SAMPLE
Enumeration Type Documentation
INIT_STATUS
enum INIT_STATUS
Enumerator
INIT_OK
REVISION_FAILED
REVISION_FALSE
RESET_FAILED
CONFIG_FAILED
SPO2_CONFIG_FAILED
INITIAL_TEMP_FAILED
LED_CONFIG_FAILED
RES_SEN_FAILED
RES_SEN_SUCCESS
GET_REG_FAILED
GET_REG_SUCCESS
SET_REG_FAILED
SET_REG_SUCCESS
FLAG_SET
FLAG_NOT_SET
FIFO_READ_SUCCESS
FIFO_READ_FAILURE
READ_SAMPLE_SET_SUCCESS
READ_SAMPLE_SET_FAILURE
CALIBRATION_SUCCESS
CALIBRATION_FAILURE
Definition at line 287 of file max30101.h.
Function Documentation
MAX30101_clear_FIFO()
INIT_STATUS MAX30101_clear_FIFO (MAX30101 * sensor)
Definition at line 266 of file max30101.c.
References FIFO_OVF_COUNTER, FIFO_RD_PTR, FIFO_WR_PTR, MAX30101_write_register(), SET_REG_FAILED, and SET_REG_SUCCESS.
MAX30101_get_FIFO_config()
INIT_STATUS MAX30101_get_FIFO_config (MAX30101 * sensor, uint8_t * reg_value)
Definition at line 275 of file max30101.c.
References FIFO_CONFIG, GET_REG_FAILED, GET_REG_SUCCESS, and MAX30101_read_register().
MAX30101_get_interr_A_FULL()
bool MAX30101_get_interr_A_FULL (MAX30101 * sensor)
Definition at line 218 of file max30101.c.
References GET_REG_SUCCESS, and MAX30101_get_interrupt_status01().
MAX30101_get_interr_PPG_RDY()
bool MAX30101_get_interr_PPG_RDY (MAX30101 * sensor)
Definition at line 236 of file max30101.c.
References MAX30101::i2c_handle, I2C_TIMEOUT, INTERRUPT_STATUS01, and MAX30101_I2C_READ.
MAX30101_get_interrupt_enabled01()
INIT_STATUS MAX30101_get_interrupt_enabled01 (MAX30101 * sensor, uint8_t * reg_value)
Definition at line 163 of file max30101.c.
References GET_REG_FAILED, GET_REG_SUCCESS, INTERRUPT_ENABLE01, and MAX30101_read_register().
MAX30101_get_interrupt_enabled02()
INIT_STATUS MAX30101_get_interrupt_enabled02 (MAX30101 * sensor, uint8_t * reg_value)
Definition at line 188 of file max30101.c.
References GET_REG_FAILED, GET_REG_SUCCESS, INTERRUPT_ENABLE02, and MAX30101_read_register().
MAX30101_get_interrupt_status01()
INIT_STATUS MAX30101_get_interrupt_status01 (MAX30101 * sensor, uint8_t * reg_value)
Definition at line 175 of file max30101.c.
References GET_REG_FAILED, GET_REG_SUCCESS, INTERRUPT_STATUS01, and MAX30101_read_register().
MAX30101_get_interrupt_status02()
INIT_STATUS MAX30101_get_interrupt_status02 (MAX30101 * sensor, uint8_t * reg_value)
Definition at line 200 of file max30101.c.
References GET_REG_FAILED, GET_REG_SUCCESS, INTERRUPT_STATUS02, and MAX30101_read_register().
MAX30101_get_LED1_PA_config()
INIT_STATUS MAX30101_get_LED1_PA_config (MAX30101 * sensor, uint8_t * reg_value)
Definition at line 311 of file max30101.c.
References GET_REG_FAILED, GET_REG_SUCCESS, LED_PulseAmp_LED1_PA, and MAX30101_read_register().
MAX30101_get_LED2_PA_config()
INIT_STATUS MAX30101_get_LED2_PA_config (MAX30101 * sensor, uint8_t * reg_value)
Definition at line 323 of file max30101.c.
References GET_REG_FAILED, GET_REG_SUCCESS, LED_PulseAmp_LED2_PA, and MAX30101_read_register().
MAX30101_get_LED3_PA_config()
INIT_STATUS MAX30101_get_LED3_PA_config (MAX30101 * sensor, uint8_t * reg_value)
Definition at line 335 of file max30101.c.
References GET_REG_FAILED, GET_REG_SUCCESS, LED_PulseAmp_LED3_PA, and MAX30101_read_register().
MAX30101_get_LED4_PA_config()
INIT_STATUS MAX30101_get_LED4_PA_config (MAX30101 * sensor, uint8_t * reg_value)
Definition at line 347 of file max30101.c.
References GET_REG_FAILED, GET_REG_SUCCESS, LED_PulseAmp_LED4_PA, and MAX30101_read_register().
MAX30101_get_MODE_config()
INIT_STATUS MAX30101_get_MODE_config (MAX30101 * sensor, uint8_t * reg_value)
Definition at line 287 of file max30101.c.
References GET_REG_FAILED, GET_REG_SUCCESS, MAX30101_read_register(), and MODE_CONFIG.
MAX30101_get_mulit_led_slot_0102_PA_config()
INIT_STATUS MAX30101_get_mulit_led_slot_0102_PA_config (MAX30101 * sensor, uint8_t * reg)
Definition at line 359 of file max30101.c.
References GET_REG_FAILED, GET_REG_SUCCESS, MAX30101_read_register(), and MULTI_LED_SLOT01_AND_02.
MAX30101_get_mulit_led_slot_0304_PA_config()
INIT_STATUS MAX30101_get_mulit_led_slot_0304_PA_config (MAX30101 * sensor, uint8_t * reg_value)
Definition at line 371 of file max30101.c.
References GET_REG_FAILED, GET_REG_SUCCESS, MAX30101_read_register(), and MULTI_LED_SLOT03_AND_04.
MAX30101_get_SPO2_config()
INIT_STATUS MAX30101_get_SPO2_config (MAX30101 * sensor, uint8_t * reg_value)
Definition at line 299 of file max30101.c.
References GET_REG_FAILED, GET_REG_SUCCESS, MAX30101_read_register(), and SPO2_CONFIG.
MAX30101_get_temp_frac_int()
INIT_STATUS MAX30101_get_temp_frac_int (MAX30101 * sensor, uint8_t * reg_value)
Definition at line 389 of file max30101.c.
References GET_REG_FAILED, GET_REG_SUCCESS, MAX30101_read_register(), and TEMP_FRACTION.
MAX30101_get_temp_int()
INIT_STATUS MAX30101_get_temp_int (MAX30101 * sensor, uint8_t * reg_value)
Definition at line 383 of file max30101.c.
References GET_REG_FAILED, GET_REG_SUCCESS, MAX30101_read_register(), and TEMP_INTEGER.
MAX30101_initialize()
INIT_STATUS MAX30101_initialize (MAX30101 * sensor)
Definition at line 75 of file max30101.c.
References CONFIG_FAILED, DIE_TEMP_RDY, FIFO_A_FULL_24, FIFO_ROLLOVER_DIS, FIFO_SMP_AVE_32, IE01_A_FULL_EN, IE01_ALC_OVF_EN, IE01_PPG_RDY_EN, INIT_OK, MAX30101_reset(), MAX30101_set_FIFO_config(), MAX30101_set_interrupt_enabled01(), MAX30101_set_interrupt_enabled02(), MAX30101_set_LED1_PA_config(), MAX30101_set_LED2_PA_config(), MAX30101_set_LED3_PA_config(), MAX30101_set_LED4_PA_config(), MAX30101_set_MODE_config(), MAX30101_set_mulit_led_slot_0102_PA_config(), MAX30101_set_mulit_led_slot_0304_PA_config(), MAX30101_set_SPO2_config(), MODE_HR, RES_SEN_SUCCESS, SET_REG_SUCCESS, SPO2_ADC_RGE_00, SPO2_LED_PW69, and SPO2_SR_3200.
MAX30101_read_register()
HAL_StatusTypeDef MAX30101_read_register (MAX30101 * sensor, uint8_t reg, uint8_t * data)
Definition at line 410 of file max30101.c.
References MAX30101::i2c_handle, I2C_TIMEOUT, and MAX30101_I2C_READ.
MAX30101_read_registers()
HAL_StatusTypeDef MAX30101_read_registers (MAX30101 * sensor, uint8_t reg, uint8_t * data, uint8_t size)
Definition at line 423 of file max30101.c.
References MAX30101::i2c_handle, I2C_TIMEOUT, and MAX30101_I2C_READ.
MAX30101_read_sample()
INIT_STATUS MAX30101_read_sample (MAX30101 * sensor, MAX30101_SAMPLE * sample)
Definition at line 127 of file max30101.c.
References ACTIVE_LED_CHANNELS, FIFO_DATA, GET_REG_FAILED, GET_REG_SUCCESS, MAX30101::i2c_handle, I2C_TIMEOUT, MAX30101_I2C_READ, MAX30101_SAMPLE::red_led_value, and MAX30101_SAMPLE::tick_time.
MAX30101_reset()
INIT_STATUS MAX30101_reset (MAX30101 * sensor)
Definition at line 154 of file max30101.c.
References MAX30101_set_MODE_config(), RES_SEN_FAILED, RES_SEN_SUCCESS, and SET_REG_SUCCESS.
MAX30101_set_FIFO_config()
INIT_STATUS MAX30101_set_FIFO_config (MAX30101 * sensor, uint8_t * reg_value)
Definition at line 281 of file max30101.c.
References FIFO_CONFIG, MAX30101_write_register(), SET_REG_FAILED, and SET_REG_SUCCESS.
MAX30101_set_interrupt_enabled01()
INIT_STATUS MAX30101_set_interrupt_enabled01 (MAX30101 * sensor, uint8_t * reg_value)
Definition at line 169 of file max30101.c.
References INTERRUPT_ENABLE01, MAX30101_write_register(), SET_REG_FAILED, and SET_REG_SUCCESS.
MAX30101_set_interrupt_enabled02()
INIT_STATUS MAX30101_set_interrupt_enabled02 (MAX30101 * sensor, uint8_t * reg_value)
Definition at line 194 of file max30101.c.
References INTERRUPT_ENABLE02, MAX30101_write_register(), SET_REG_FAILED, and SET_REG_SUCCESS.
MAX30101_set_interrupt_status01()
INIT_STATUS MAX30101_set_interrupt_status01 (MAX30101 * sensor, uint8_t * reg_value)
Definition at line 181 of file max30101.c.
References INTERRUPT_STATUS02, MAX30101_write_register(), SET_REG_FAILED, and SET_REG_SUCCESS.
MAX30101_set_interrupt_status02()
INIT_STATUS MAX30101_set_interrupt_status02 (MAX30101 * sensor, uint8_t * reg_value)
Definition at line 206 of file max30101.c.
References INTERRUPT_STATUS02, MAX30101_write_register(), SET_REG_FAILED, and SET_REG_SUCCESS.
MAX30101_set_LED1_PA_config()
INIT_STATUS MAX30101_set_LED1_PA_config (MAX30101 * sensor, uint8_t * reg_value)
Definition at line 317 of file max30101.c.
References LED_PulseAmp_LED1_PA, MAX30101_write_register(), SET_REG_FAILED, and SET_REG_SUCCESS.
MAX30101_set_LED2_PA_config()
INIT_STATUS MAX30101_set_LED2_PA_config (MAX30101 * sensor, uint8_t * reg_value)
Definition at line 329 of file max30101.c.
References LED_PulseAmp_LED2_PA, MAX30101_write_register(), SET_REG_FAILED, and SET_REG_SUCCESS.
MAX30101_set_LED3_PA_config()
INIT_STATUS MAX30101_set_LED3_PA_config (MAX30101 * sensor, uint8_t * reg_value)
Definition at line 341 of file max30101.c.
References LED_PulseAmp_LED3_PA, MAX30101_write_register(), SET_REG_FAILED, and SET_REG_SUCCESS.
MAX30101_set_LED4_PA_config()
INIT_STATUS MAX30101_set_LED4_PA_config (MAX30101 * sensor, uint8_t * reg_value)
Definition at line 353 of file max30101.c.
References LED_PulseAmp_LED4_PA, MAX30101_write_register(), SET_REG_FAILED, and SET_REG_SUCCESS.
MAX30101_set_MODE_config()
INIT_STATUS MAX30101_set_MODE_config (MAX30101 * sensor, uint8_t * reg_value)
Definition at line 293 of file max30101.c.
References MAX30101_write_register(), MODE_CONFIG, SET_REG_FAILED, and SET_REG_SUCCESS.
MAX30101_set_mulit_led_slot_0102_PA_config()
INIT_STATUS MAX30101_set_mulit_led_slot_0102_PA_config (MAX30101 * sensor, uint8_t * reg)
Definition at line 365 of file max30101.c.
References MAX30101_write_register(), MULTI_LED_SLOT01_AND_02, SET_REG_FAILED, and SET_REG_SUCCESS.
MAX30101_set_mulit_led_slot_0304_PA_config()
INIT_STATUS MAX30101_set_mulit_led_slot_0304_PA_config (MAX30101 * sensor, uint8_t * reg_value)
Definition at line 377 of file max30101.c.
References MAX30101_write_register(), MULTI_LED_SLOT03_AND_04, SET_REG_FAILED, and SET_REG_SUCCESS.
MAX30101_set_SPO2_config()
INIT_STATUS MAX30101_set_SPO2_config (MAX30101 * sensor, uint8_t * reg_value)
Definition at line 305 of file max30101.c.
References MAX30101_write_register(), SET_REG_FAILED, SET_REG_SUCCESS, and SPO2_CONFIG.
MAX30101_set_temp_en_int()
INIT_STATUS MAX30101_set_temp_en_int (MAX30101 * sensor, uint8_t * reg_value)
Definition at line 395 of file max30101.c.
References GET_REG_FAILED, GET_REG_SUCCESS, MAX30101_read_register(), and TEMP_EN.
MAX30101_write_register()
HAL_StatusTypeDef MAX30101_write_register (MAX30101 * sensor, uint8_t reg, uint8_t * data)
Definition at line 435 of file max30101.c.
References MAX30101::i2c_handle, I2C_TIMEOUT, and MAX30101_I2C_WRITE.
translate_I2C_Error()
void translate_I2C_Error (I2C_HandleTypeDef * hi2c)
Definition at line 25 of file max30101.c.
References printf_().
Variable Documentation
huart2
UART_HandleTypeDef huart2
Definition at line 49 of file main.c.