Project DreamTeam: Core/Src/max30101.c File Reference
max30101.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include "max30101.h"
#include "stm32l4xx_hal.h"
#include "printf.h"
#include "stm32l4xx_ll_i2c.h"
Functions
void translate_I2C_Error (I2C_HandleTypeDef *hi2c)
INIT_STATUS MAX30101_initialize (MAX30101 *sensor)
INIT_STATUS MAX30101_read_sample (MAX30101 *sensor, MAX30101_SAMPLE *sample)
INIT_STATUS MAX30101_reset (MAX30101 *sensor)
INIT_STATUS MAX30101_get_interrupt_enabled01 (MAX30101 *sensor, uint8_t *reg_value)
INIT_STATUS MAX30101_set_interrupt_enabled01 (MAX30101 *sensor, uint8_t *reg_value)
INIT_STATUS MAX30101_get_interrupt_status01 (MAX30101 *sensor, uint8_t *reg_value)
INIT_STATUS MAX30101_set_interrupt_status01 (MAX30101 *sensor, uint8_t *reg_value)
INIT_STATUS MAX30101_get_interrupt_enabled02 (MAX30101 *sensor, uint8_t *reg_value)
INIT_STATUS MAX30101_set_interrupt_enabled02 (MAX30101 *sensor, uint8_t *reg_value)
INIT_STATUS MAX30101_get_interrupt_status02 (MAX30101 *sensor, uint8_t *reg_value)
INIT_STATUS MAX30101_set_interrupt_status02 (MAX30101 *sensor, uint8_t *reg_value)
bool MAX30101_get_interr_A_FULL (MAX30101 *sensor)
bool MAX30101_get_interr_PPG_RDY (MAX30101 *sensor)
INIT_STATUS MAX30101_get_interr_DIE_TEMP_RDY (MAX30101 *sensor)
INIT_STATUS MAX30101_clear_FIFO (MAX30101 *sensor)
INIT_STATUS MAX30101_get_FIFO_config (MAX30101 *sensor, uint8_t *reg_value)
INIT_STATUS MAX30101_set_FIFO_config (MAX30101 *sensor, uint8_t *reg_value)
INIT_STATUS MAX30101_get_MODE_config (MAX30101 *sensor, uint8_t *reg_value)
INIT_STATUS MAX30101_set_MODE_config (MAX30101 *sensor, uint8_t *reg_value)
INIT_STATUS MAX30101_get_SPO2_config (MAX30101 *sensor, uint8_t *reg_value)
INIT_STATUS MAX30101_set_SPO2_config (MAX30101 *sensor, uint8_t *reg_value)
INIT_STATUS MAX30101_get_LED1_PA_config (MAX30101 *sensor, uint8_t *reg_value)
INIT_STATUS MAX30101_set_LED1_PA_config (MAX30101 *sensor, uint8_t *reg_value)
INIT_STATUS MAX30101_get_LED2_PA_config (MAX30101 *sensor, uint8_t *reg_value)
INIT_STATUS MAX30101_set_LED2_PA_config (MAX30101 *sensor, uint8_t *reg_value)
INIT_STATUS MAX30101_get_LED3_PA_config (MAX30101 *sensor, uint8_t *reg_value)
INIT_STATUS MAX30101_set_LED3_PA_config (MAX30101 *sensor, uint8_t *reg_value)
INIT_STATUS MAX30101_get_LED4_PA_config (MAX30101 *sensor, uint8_t *reg_value)
INIT_STATUS MAX30101_set_LED4_PA_config (MAX30101 *sensor, uint8_t *reg_value)
INIT_STATUS MAX30101_get_mulit_led_slot_0102_PA_config (MAX30101 *sensor, uint8_t *reg)
INIT_STATUS MAX30101_set_mulit_led_slot_0102_PA_config (MAX30101 *sensor, uint8_t *reg_value)
INIT_STATUS MAX30101_get_mulit_led_slot_0304_PA_config (MAX30101 *sensor, uint8_t *reg_value)
INIT_STATUS MAX30101_set_mulit_led_slot_0304_PA_config (MAX30101 *sensor, uint8_t *reg_value)
INIT_STATUS MAX30101_get_temp_int (MAX30101 *sensor, uint8_t *reg_value)
INIT_STATUS MAX30101_get_temp_frac_int (MAX30101 *sensor, uint8_t *reg_value)
INIT_STATUS MAX30101_set_temp_en_int (MAX30101 *sensor, uint8_t *reg_value)
HAL_StatusTypeDef MAX30101_read_register (MAX30101 *sensor, uint8_t reg, uint8_t *data)
HAL_StatusTypeDef MAX30101_read_registers (MAX30101 *sensor, uint8_t reg, uint8_t *data, uint8_t size)
HAL_StatusTypeDef MAX30101_write_register (MAX30101 *sensor, uint8_t reg, uint8_t *data)
Function Documentation
MAX30101_clear_FIFO()
INIT_STATUS MAX30101_clear_FIFO (MAX30101 * sensor)
Definition at line 266 of file max30101.c.
References FIFO_OVF_COUNTER, FIFO_RD_PTR, FIFO_WR_PTR, MAX30101_write_register(), SET_REG_FAILED, and SET_REG_SUCCESS.
MAX30101_get_FIFO_config()
INIT_STATUS MAX30101_get_FIFO_config (MAX30101 * sensor, uint8_t * reg_value)
Definition at line 275 of file max30101.c.
References FIFO_CONFIG, GET_REG_FAILED, GET_REG_SUCCESS, and MAX30101_read_register().
MAX30101_get_interr_A_FULL()
bool MAX30101_get_interr_A_FULL (MAX30101 * sensor)
Definition at line 218 of file max30101.c.
References GET_REG_SUCCESS, and MAX30101_get_interrupt_status01().
MAX30101_get_interr_DIE_TEMP_RDY()
INIT_STATUS MAX30101_get_interr_DIE_TEMP_RDY (MAX30101 * sensor)
Definition at line 250 of file max30101.c.
References FLAG_NOT_SET, FLAG_SET, GET_REG_SUCCESS, and MAX30101_get_interrupt_status02().
MAX30101_get_interr_PPG_RDY()
bool MAX30101_get_interr_PPG_RDY (MAX30101 * sensor)
Definition at line 236 of file max30101.c.
References MAX30101::i2c_handle, I2C_TIMEOUT, INTERRUPT_STATUS01, and MAX30101_I2C_READ.
MAX30101_get_interrupt_enabled01()
INIT_STATUS MAX30101_get_interrupt_enabled01 (MAX30101 * sensor, uint8_t * reg_value)
Definition at line 163 of file max30101.c.
References GET_REG_FAILED, GET_REG_SUCCESS, INTERRUPT_ENABLE01, and MAX30101_read_register().
MAX30101_get_interrupt_enabled02()
INIT_STATUS MAX30101_get_interrupt_enabled02 (MAX30101 * sensor, uint8_t * reg_value)
Definition at line 188 of file max30101.c.
References GET_REG_FAILED, GET_REG_SUCCESS, INTERRUPT_ENABLE02, and MAX30101_read_register().
MAX30101_get_interrupt_status01()
INIT_STATUS MAX30101_get_interrupt_status01 (MAX30101 * sensor, uint8_t * reg_value)
Definition at line 175 of file max30101.c.
References GET_REG_FAILED, GET_REG_SUCCESS, INTERRUPT_STATUS01, and MAX30101_read_register().
MAX30101_get_interrupt_status02()
INIT_STATUS MAX30101_get_interrupt_status02 (MAX30101 * sensor, uint8_t * reg_value)
Definition at line 200 of file max30101.c.
References GET_REG_FAILED, GET_REG_SUCCESS, INTERRUPT_STATUS02, and MAX30101_read_register().
MAX30101_get_LED1_PA_config()
INIT_STATUS MAX30101_get_LED1_PA_config (MAX30101 * sensor, uint8_t * reg_value)
Definition at line 311 of file max30101.c.
References GET_REG_FAILED, GET_REG_SUCCESS, LED_PulseAmp_LED1_PA, and MAX30101_read_register().
MAX30101_get_LED2_PA_config()
INIT_STATUS MAX30101_get_LED2_PA_config (MAX30101 * sensor, uint8_t * reg_value)
Definition at line 323 of file max30101.c.
References GET_REG_FAILED, GET_REG_SUCCESS, LED_PulseAmp_LED2_PA, and MAX30101_read_register().
MAX30101_get_LED3_PA_config()
INIT_STATUS MAX30101_get_LED3_PA_config (MAX30101 * sensor, uint8_t * reg_value)
Definition at line 335 of file max30101.c.
References GET_REG_FAILED, GET_REG_SUCCESS, LED_PulseAmp_LED3_PA, and MAX30101_read_register().
MAX30101_get_LED4_PA_config()
INIT_STATUS MAX30101_get_LED4_PA_config (MAX30101 * sensor, uint8_t * reg_value)
Definition at line 347 of file max30101.c.
References GET_REG_FAILED, GET_REG_SUCCESS, LED_PulseAmp_LED4_PA, and MAX30101_read_register().
MAX30101_get_MODE_config()
INIT_STATUS MAX30101_get_MODE_config (MAX30101 * sensor, uint8_t * reg_value)
Definition at line 287 of file max30101.c.
References GET_REG_FAILED, GET_REG_SUCCESS, MAX30101_read_register(), and MODE_CONFIG.
MAX30101_get_mulit_led_slot_0102_PA_config()
INIT_STATUS MAX30101_get_mulit_led_slot_0102_PA_config (MAX30101 * sensor, uint8_t * reg)
Definition at line 359 of file max30101.c.
References GET_REG_FAILED, GET_REG_SUCCESS, MAX30101_read_register(), and MULTI_LED_SLOT01_AND_02.
MAX30101_get_mulit_led_slot_0304_PA_config()
INIT_STATUS MAX30101_get_mulit_led_slot_0304_PA_config (MAX30101 * sensor, uint8_t * reg_value)
Definition at line 371 of file max30101.c.
References GET_REG_FAILED, GET_REG_SUCCESS, MAX30101_read_register(), and MULTI_LED_SLOT03_AND_04.
MAX30101_get_SPO2_config()
INIT_STATUS MAX30101_get_SPO2_config (MAX30101 * sensor, uint8_t * reg_value)
Definition at line 299 of file max30101.c.
References GET_REG_FAILED, GET_REG_SUCCESS, MAX30101_read_register(), and SPO2_CONFIG.
MAX30101_get_temp_frac_int()
INIT_STATUS MAX30101_get_temp_frac_int (MAX30101 * sensor, uint8_t * reg_value)
Definition at line 389 of file max30101.c.
References GET_REG_FAILED, GET_REG_SUCCESS, MAX30101_read_register(), and TEMP_FRACTION.
MAX30101_get_temp_int()
INIT_STATUS MAX30101_get_temp_int (MAX30101 * sensor, uint8_t * reg_value)
Definition at line 383 of file max30101.c.
References GET_REG_FAILED, GET_REG_SUCCESS, MAX30101_read_register(), and TEMP_INTEGER.
MAX30101_initialize()
INIT_STATUS MAX30101_initialize (MAX30101 * sensor)
Definition at line 75 of file max30101.c.
References CONFIG_FAILED, DIE_TEMP_RDY, FIFO_A_FULL_24, FIFO_ROLLOVER_DIS, FIFO_SMP_AVE_32, IE01_A_FULL_EN, IE01_ALC_OVF_EN, IE01_PPG_RDY_EN, INIT_OK, MAX30101_reset(), MAX30101_set_FIFO_config(), MAX30101_set_interrupt_enabled01(), MAX30101_set_interrupt_enabled02(), MAX30101_set_LED1_PA_config(), MAX30101_set_LED2_PA_config(), MAX30101_set_LED3_PA_config(), MAX30101_set_LED4_PA_config(), MAX30101_set_MODE_config(), MAX30101_set_mulit_led_slot_0102_PA_config(), MAX30101_set_mulit_led_slot_0304_PA_config(), MAX30101_set_SPO2_config(), MODE_HR, RES_SEN_SUCCESS, SET_REG_SUCCESS, SPO2_ADC_RGE_00, SPO2_LED_PW69, and SPO2_SR_3200.
MAX30101_read_register()
HAL_StatusTypeDef MAX30101_read_register (MAX30101 * sensor, uint8_t reg, uint8_t * data)
Definition at line 410 of file max30101.c.
References MAX30101::i2c_handle, I2C_TIMEOUT, and MAX30101_I2C_READ.
MAX30101_read_registers()
HAL_StatusTypeDef MAX30101_read_registers (MAX30101 * sensor, uint8_t reg, uint8_t * data, uint8_t size)
Definition at line 423 of file max30101.c.
References MAX30101::i2c_handle, I2C_TIMEOUT, and MAX30101_I2C_READ.
MAX30101_read_sample()
INIT_STATUS MAX30101_read_sample (MAX30101 * sensor, MAX30101_SAMPLE * sample)
Definition at line 127 of file max30101.c.
References ACTIVE_LED_CHANNELS, FIFO_DATA, GET_REG_FAILED, GET_REG_SUCCESS, MAX30101::i2c_handle, I2C_TIMEOUT, MAX30101_I2C_READ, MAX30101_SAMPLE::red_led_value, and MAX30101_SAMPLE::tick_time.
MAX30101_reset()
INIT_STATUS MAX30101_reset (MAX30101 * sensor)
Definition at line 154 of file max30101.c.
References MAX30101_set_MODE_config(), RES_SEN_FAILED, RES_SEN_SUCCESS, and SET_REG_SUCCESS.
MAX30101_set_FIFO_config()
INIT_STATUS MAX30101_set_FIFO_config (MAX30101 * sensor, uint8_t * reg_value)
Definition at line 281 of file max30101.c.
References FIFO_CONFIG, MAX30101_write_register(), SET_REG_FAILED, and SET_REG_SUCCESS.
MAX30101_set_interrupt_enabled01()
INIT_STATUS MAX30101_set_interrupt_enabled01 (MAX30101 * sensor, uint8_t * reg_value)
Definition at line 169 of file max30101.c.
References INTERRUPT_ENABLE01, MAX30101_write_register(), SET_REG_FAILED, and SET_REG_SUCCESS.
MAX30101_set_interrupt_enabled02()
INIT_STATUS MAX30101_set_interrupt_enabled02 (MAX30101 * sensor, uint8_t * reg_value)
Definition at line 194 of file max30101.c.
References INTERRUPT_ENABLE02, MAX30101_write_register(), SET_REG_FAILED, and SET_REG_SUCCESS.
MAX30101_set_interrupt_status01()
INIT_STATUS MAX30101_set_interrupt_status01 (MAX30101 * sensor, uint8_t * reg_value)
Definition at line 181 of file max30101.c.
References INTERRUPT_STATUS02, MAX30101_write_register(), SET_REG_FAILED, and SET_REG_SUCCESS.
MAX30101_set_interrupt_status02()
INIT_STATUS MAX30101_set_interrupt_status02 (MAX30101 * sensor, uint8_t * reg_value)
Definition at line 206 of file max30101.c.
References INTERRUPT_STATUS02, MAX30101_write_register(), SET_REG_FAILED, and SET_REG_SUCCESS.
MAX30101_set_LED1_PA_config()
INIT_STATUS MAX30101_set_LED1_PA_config (MAX30101 * sensor, uint8_t * reg_value)
Definition at line 317 of file max30101.c.
References LED_PulseAmp_LED1_PA, MAX30101_write_register(), SET_REG_FAILED, and SET_REG_SUCCESS.
MAX30101_set_LED2_PA_config()
INIT_STATUS MAX30101_set_LED2_PA_config (MAX30101 * sensor, uint8_t * reg_value)
Definition at line 329 of file max30101.c.
References LED_PulseAmp_LED2_PA, MAX30101_write_register(), SET_REG_FAILED, and SET_REG_SUCCESS.
MAX30101_set_LED3_PA_config()
INIT_STATUS MAX30101_set_LED3_PA_config (MAX30101 * sensor, uint8_t * reg_value)
Definition at line 341 of file max30101.c.
References LED_PulseAmp_LED3_PA, MAX30101_write_register(), SET_REG_FAILED, and SET_REG_SUCCESS.
MAX30101_set_LED4_PA_config()
INIT_STATUS MAX30101_set_LED4_PA_config (MAX30101 * sensor, uint8_t * reg_value)
Definition at line 353 of file max30101.c.
References LED_PulseAmp_LED4_PA, MAX30101_write_register(), SET_REG_FAILED, and SET_REG_SUCCESS.
MAX30101_set_MODE_config()
INIT_STATUS MAX30101_set_MODE_config (MAX30101 * sensor, uint8_t * reg_value)
Definition at line 293 of file max30101.c.
References MAX30101_write_register(), MODE_CONFIG, SET_REG_FAILED, and SET_REG_SUCCESS.
MAX30101_set_mulit_led_slot_0102_PA_config()
INIT_STATUS MAX30101_set_mulit_led_slot_0102_PA_config (MAX30101 * sensor, uint8_t * reg_value)
Definition at line 365 of file max30101.c.
References MAX30101_write_register(), MULTI_LED_SLOT01_AND_02, SET_REG_FAILED, and SET_REG_SUCCESS.
MAX30101_set_mulit_led_slot_0304_PA_config()
INIT_STATUS MAX30101_set_mulit_led_slot_0304_PA_config (MAX30101 * sensor, uint8_t * reg_value)
Definition at line 377 of file max30101.c.
References MAX30101_write_register(), MULTI_LED_SLOT03_AND_04, SET_REG_FAILED, and SET_REG_SUCCESS.
MAX30101_set_SPO2_config()
INIT_STATUS MAX30101_set_SPO2_config (MAX30101 * sensor, uint8_t * reg_value)
Definition at line 305 of file max30101.c.
References MAX30101_write_register(), SET_REG_FAILED, SET_REG_SUCCESS, and SPO2_CONFIG.
MAX30101_set_temp_en_int()
INIT_STATUS MAX30101_set_temp_en_int (MAX30101 * sensor, uint8_t * reg_value)
Definition at line 395 of file max30101.c.
References GET_REG_FAILED, GET_REG_SUCCESS, MAX30101_read_register(), and TEMP_EN.
MAX30101_write_register()
HAL_StatusTypeDef MAX30101_write_register (MAX30101 * sensor, uint8_t reg, uint8_t * data)
Definition at line 435 of file max30101.c.
References MAX30101::i2c_handle, I2C_TIMEOUT, and MAX30101_I2C_WRITE.
translate_I2C_Error()
void translate_I2C_Error (I2C_HandleTypeDef * hi2c)
Definition at line 25 of file max30101.c.
References printf_().